### ISSUE TITLE
History should store no duplicate

### ISSUE THREAD

**Issue by Ambrevar** [The-Compiler/qutebrowser#1030]
The history will grow big. Very. Quickly.
I suggest on every history insertion you remove any former duplicate. It is more important to keep last access date.

**Comment by The-Compiler** [comment]
Currently qutebrowser doesn't touch/rewrite the old history at all - it always only opens the file in append mode.

I'm not sure if it's really a problem - even with 100k lines in my history since February, the file is 7 MB, which isn't *that* big.

#58 is somewhat related, which would give an user the possibility to keep a given time period of history and delete the rest on exit.

I'd like to keep the duplicates in the file, as it's useful data (e.g. to, at some point, sort the completion based on how many times the given page was accessed).

Closing this for now because there's #58, unless you have some good idea how to solve this which I didn't have yet :wink:
