### ISSUE TITLE
Hints won't follow wrapped links

### ISSUE THREAD

**Issue by Ambrevar** [The-Compiler/qutebrowser#1034]
Take a long, multiple word link, resize your window so that the link goes over 2 lines at least. The hint will display at the beginning of the line instead of over the link. And the hint won't follow.

**Comment by The-Compiler** [comment]
This was mentioned in #70 but it's probably good to have a separate issue for this.

The only way to fix this is AFAIK to get the element geometry via javascript instead of via the C++/Python API (see [QTBUG-38698](https://bugreports.qt.io/browse/QTBUG-38698) which I opened 1.5 years ago...) - and before I do that, I'd like tests for all those funny corner cases :wink:

**Comment by The-Compiler** [comment]
Closing this in favour of #1182 as I always search for "multi-line" when searching for this issue :wink:
