### ISSUE TITLE
:pyeval command

### ISSUE THREAD

**Issue by cosminadrianpopescu** [The-Compiler/qutebrowser#1156]
I was thinking of having a `pyeval` command like `jseval` outside of the debug mode and which would not open the output window. This, combined with a two way socket communication would give the developers the power to extend the browser by accessing all its internals. 

For example, I could have a userscript which would do: 

`echo 'pyeval("app = objreg.get(\"app\")\ndo_something_with_app")' >> $QUTE_FIFO`

So, we could have user scripts accessing the `QWebView` object. I would be interested in developping something like this.

What do you think?

**Comment by The-Compiler** [comment]
I'd welcome an addition like a `--quiet` flag to `:pyeval` which doesn't open the result page.

However, I really don't want to endorse userscripts using `:pyeval`, or make it an official command. I'll look into a real plugin API (which is probably the better way of doing sophisticated stuff) in #30 - however, I know a lot of stuff will be refactored in the future (as part of the QtWebEngine backend #666 and others). This is the reason there isn't a plugin API yet, I don't want to break plugins all few weeks (there's Firefox for that).

When userscripts use `:pyeval`, you'll have the same issue as above, just even worse, because there's no concept of a private/public API involved then.

**Comment by The-Compiler** [comment]
I added `--quiet` now as I needed it myself, so I'm closing this.
