### ISSUE TITLE
Better way to save sessions

### ISSUE THREAD

**Issue by fm4d** [The-Compiler/qutebrowser#1177]
Currently qutebrowser saves session only if ended properly, so whenever it crashes (and that is unfortunately multiple times every day) the session is lost. What about saving session whenever tab is opened/closed or in some different crash-proof way?

**Comment by The-Compiler** [comment]
> whenever it crashes (and that is unfortunately multiple times every day)

What OS are you on, and what Qt version (see `:open qute:version`)? I'm not aware of any crashes except on Facebook and Twitter with Qt 5.5.1.

> What about saving session whenever tab is opened/closed or in some different crash-proof way?

The reason I've not looked at this yet is that you need some UI to select *what* to restore, otherwise the restored pages will likely just crash again. See #11, so I'm closing this.

**Comment by fm4d** [comment]
I use archlinux, Qt version is 5.5.1. I am quite sure that multiple segfaults occured without twitter/facebook, so Ill wait for next one and start an issue with traceback if thats ok.

**Comment by The-Compiler** [comment]
You can - unfortunately the chances are very high I won't be able to do anything about it. Upstream is unlikely to care about QtWebKit bugs by now as it's deprecated and I lack the time to fix them myself.

Things will get better in the future with QtWebEngine however, see #666.
