### ISSUE TITLE
User CSS @document support?

### ISSUE THREAD

**Issue by tomxtobin** [The-Compiler/qutebrowser#1181]
I've been really eager for some sort of per-domain user CSS support in qutebrowser, and while it looks like #27 is the anticipated path to make this happen, I wondered if there was another way via [@document at-rules][1].

With that in mind, I threw together a stylesheet transformer library (which I still need to clean up and push to PyPI). Given a stylesheet and a URL, it strips all non-matching `@document` blocks from the transformed output.

I then hooked into the relevant places in qutebrowser (e.g., opening a new URL, forward/back, restoring sessions), transformed the global user stylesheet using the aforementioned library and the current URL, and added it as a `data:` user stylesheet to the current WebView's local settings.

It seems to work well, lets me maintain my entire user CSS in a single file, and goes a long way toward keeping me sane on the Web. ;-)

Would the project be open to adopting this approach if I cleaned everything up and submitted it as a PR? I'm happy using it locally, but I could understand that it might conflict with the intention of using the #27 approach for per-domain user styles.

[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/@document

**Comment by The-Compiler** [comment]
Hmm, can you show some code, even not cleaned up?

I'm afraid I'd probably rather not have this in qutebrowser right now. My focus is currently on tests and then the QtWebEngine backend, and anything which adds complexity and makes things more difficult is something I'm opposed to, even when I clearly see why you want per-URL stylesheets. :wink:

Also it'd mean adding a new, unpackaged dependency (which can be problematic for distributions) for a temporary workaround, which is another reason why I'd rather do this in a generic way after the QtWebEngine thing is taken care of.

**Comment by tomxtobin** [comment]
> Hmm, can you show some code, even not cleaned up?

[Here you go][1], with the caveats given. (I feel like I'm showing my dirty laundry.) ;-) You can't even run it yet, since I haven't published cssdocument to PyPI, but you can get an idea of what I'm trying.

[1]: https://github.com/tomxtobin/qutebrowser/commit/3009a9686cd5d802c978014a2f629cfcf855021c

> I'm afraid I'd probably rather not have this in qutebrowser right now. My focus is currently on tests and then the QtWebEngine backend, and anything which adds complexity and makes things more difficult is something I'm opposed to, even when I clearly see why you want per-URL stylesheets. :wink:

Totally understandable; that's why I figured I'd ask before putting the effort into making it fit for a PR. I'm quite happy using it locally, so it scratched my itch. ;-)

> Also it'd mean adding a new, unpackaged dependency (which can be problematic for distributions) for a temporary workaround, which is another reason why I'd rather do this in a generic way after the QtWebEngine thing is taken care of.

Yeah, I get that, too. I do plan on packaging and publishing cssdocument sometime soon, so maybe that could help form the basis of a more proper solution down the road. I do think there's merit to the `@document` approach insofar as the end user's ease-of-use: there's only one file to maintain, and `@document` is already something of a quasi-standard.

**Comment by The-Compiler** [comment]
By the way, why not include the `@document` splitting in [cssutils](https://pythonhosted.org/cssutils/) instead of releasing it as a separate project? cssutils is already an optional dependency of qutebrowser, and @Kingdread (who's also a qutebrowser contributor) basically ended up being the maintainer of it :wink:

**Comment by tomxtobin** [comment]
> By the way, why not include the `@document` splitting in cssutils instead of releasing it as a separate project?

A few reasons:

- I based it on [tinycss2][1], which ended up being really easy. tinycss2 is kinda "dumb" in a good way, in that it doesn't care about *what* the various rules do when building its AST, so it makes it simple to write CSS transformers. It's fairly future-proof in that sense: it's probably still going to do the right thing when encountering an unknown rule, which makes it the right approach for a straight source-to-source transform IMHO. cssutils tries to understand the syntax on a more meaningful level, so I'm not sure if it would handle this sort of "dumb", "just do what I want" transform as well.

[1]: https://github.com/SimonSapin/tinycss2

- I'd like to make the functionality available in a liberally licensed way for maximal reuse (MIT); tinycss2 is also liberally licensed (BSD).

- And the real kicker: [cssutils is using Mercurial][2]. I've had nothing but absolutely horrible experiences with Mercurial and I've sworn off contributing to any projects using it. (Or not using Git, period, for that matter.) ;-)

[2]: https://bitbucket.org/cthedot/cssutils

If it wasn't for that last point, I wouldn't be opposed to also contributing a patch with `@document` support to cssutils if it looked feasible, especially if it meant helping qutebrowser down the road. But, oh, ye gods, Mercurial just doesn't agree with my brain. o_O

**Comment by The-Compiler** [comment]
> But, oh, ye gods, Mercurial just doesn't agree with my brain. o_O

I feel your pain... That's why I helped pytest and pylint to migrate from Bitbucket to GitHub :wink:

**Comment by vyp** [comment]
Ugh same about mercurial! And it's supposed to be easier than git too! Or at least that's what they clai! (I don't know if I'm just too used to the git way or something.)

If it isn't too complicated of a patch, mercurial does have `hg export`, which is basically just like git's `format-patch` (I think). i.e. creates a patch file. So if it's the branching (or what do they call it, labels or anonymous branches or something?) that's preventing you from submitting a patch, maybe you can just hg clone, then simply make your changes, and hg export and send the resultant patch file?

**Comment by tomxtobin** [comment]
I don't want to get into a "Git rules! Mercurial sucks!" rant here. :-) It's not my say which VCS a project decides to use, unless it's my project. I just find myself a bit disheartened whenever I see an interesting project *not* using Git, because the trade-off of dealing with another VCS just isn't worth it to me — it's too much friction. I'd rather go find something else that *does* use Git, or just write my own thing. (Which is a shame, but I find myself putting my sanity before idealism as I get older.) ;-)

> If it isn't too complicated of a patch, mercurial does have `hg export`, which is basically just like git's `format-patch` (I think). i.e. creates a patch file. So if it's the branching (or what do they call it, labels or anonymous branches or something?) that's preventing you from submitting a patch, maybe you can just hg clone, then simply make your changes, and hg export and send the resultant patch file?

But then we're reduced to a pre-VCS workflow of mailing patches around, which gets compounded if the patch in question needs any sort of review or revision. That would drive me crazy, and I'm sure it would do the same to the poor maintainer I'd be imposing upon.

**Comment by vyp** [comment]
Yeah I know, I was thinking if it's a simple enough patch, then it could work. Although there are like non-github projects which still use git, but use email (mailing lists) to submit patches through. So as in it's still "mailing patches around", but it's technically not "pre-VCS" because git is still used. :p But yeah, it was just a suggestion.

**Comment by Kingdread** [comment]
Just chiming in here, as @The-Compiler said, I ended up being a maintainer of `cssutils` (and also a contributor to `qutebrowser`) :wink:

### Some general stuff:

First off, I'm an avid git user myself, but since I didn't start `cssutils`, I didn't make the choice to use mercurial instead, in fact, it's the first time with hg for me too. I'd really like to move `cssutils` to git(hub), maybe add some CI, clean up the code, ... but since I'm not the owner, I'm a bit reluctant to do such a big change and I don't have access to update all resources. So in the end, it probably wouldn't be much better than a plain fork hosted on github, and I don't want to half-ass it :wink:

Secondly, `cssutils` is licensed under the LGPL, which means you can use it fine even in proprietary software, as long as (*your modified version of*) `cssutils` itself is kept open source (though IANAL, so my understanding might not be 100% correct)

And lastly, if the only thing preventing you from contributing is mercurial, I'm open to accept patches via email (exported using `hg export` or `hg diff`). If your change is bigger and/or needs more review, I could also provide a git-based clone on github, so you could do a PR here and I would incorporate the changes in the mercurial repository. If you want something like that (email or github), feel free to contact me and I can set something up.

### Now for this specific issue:

Seems like `cssutils` can't parse `@document` rules yet, as support for CSS 3 grammar isn't finished \*cough\* (see also [issue 57](https://bitbucket.org/cthedot/cssutils/issues/57/how-unvalidate)), so it currently isn't possible to use `cssutils` for this, at least not before *somebody* updates `cssutils` for CSS 3 (and adds a better way of dealing with unknown at-rules). So yeah, you're better off with tinycss at the moment :wink:

**Comment by tomxtobin** [comment]
Thanks, @Kingdread — now I don't have to feel guilty. ;-)

The license thing was a minor consideration; I get that cssutils isn't full-on GPL.

I'll probably end up maintaining the user stylesheet support as a branch, just in case anyone else finds it useful; it's one of the few things I had sorely missed since switching over from dwb. I'm already smacking my forehead over the way I implemented it, though (e.g., not just sticking the update code in the `urlChanged` signal handler). o_O

**Comment by seniorivn** [comment]
@tomxtobin hi, wondering, if this feature already can be used, someway?

**Comment by tomxtobin** [comment]
@seniorivn In theory, sure. I've been keeping it up-to-date in a private branch, added user-script (JS) support, and made sure it works against both backends (WebKit and WebEngine). I'd just have to publish the Python module I wrote to PyPI and push the Qutebrowser branch up.

I don't think Qutebrowser is looking to adopt the approach I took, though, so keep that in mind as far as future support goes. I *am* actively using it right now — but if I ever switched browsers, I'd stop maintaining the code, since I don't otherwise use Python anymore.

**Comment by seniorivn** [comment]
@tomxtobin that's awesome, could you give a link for the branch?
And it's ok, about maintenance.

**Comment by The-Compiler** [comment]
FWIW I'm still trying to help getting https://codereview.qt-project.org/#/c/148671/ into QtWebEngine which will make this work without any changes from qutebrowser's side.

Also, with https://github.com/The-Compiler/qutebrowser/pull/1155 (which I'll hopefully have time to look at sometime soon...) I wonder if it'd be possible to implement this without any qutebrowser code changes.
