### ISSUE TITLE
Backspace handling in numeric hint mode

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1186]
In numeric hint mode, assuming there are enough ambiguities to not trigger auto-follow:

- Reduce the number of hints by typing "foo".
- Type any digit and delete it again by pressing backspace.
- Now all hints are shown again, even though "foo" is still in the buffer.

I guess this is a bug...

**Comment by The-Compiler** [comment]
I can confirm this, sounds like a bug indeed.

**Comment by The-Compiler** [comment]
While a79c540078e8b00723bd6d6007d9bf9ffff781e4 improves the situation here, it's still kind of weird - e.g. with `test/manual/hints/issue1186.html` (which I'll add to the repo soon) now pressing backspace shows the filtered hints, but then pressing `0` (assuming `hints -> scatter = false`) shows all hints again.

Maybe this will be fixed by the subsequent renumbering commit which I haven't looked at yet.

**Comment by The-Compiler** [comment]
Yeah, fixed with the renumbering.
