### ISSUE TITLE
Issues With Asian Chinese Characters Appearing

### ISSUE THREAD

**Issue by cwmke** [The-Compiler/qutebrowser#1196]
I'm having a problem getting characters from Wiktionary and other sites as well to appear in qutebrowser.  I have the encoding set to utf-8 and have tried different fonts.  Specifically, Fira Sans, Sans, and Serif.  Sans and serif I used since I found them to be the same fonts used to render Chinese under  the content tab.  Any help will be greatly appreciated.  Below is a link to a sample page.

https://en.wiktionary.org/wiki/%E4%BD%A0%E5%A5%BD#Chinese

**Firefox**
![firefox](https://cloud.githubusercontent.com/assets/1923967/12011424/00047610-ac91-11e5-9437-ced93b468078.jpg) 

**Qutebrowser**
![qutebrowser](https://cloud.githubusercontent.com/assets/1923967/12011423/0003c170-ac91-11e5-962b-659b8a3776d5.jpg)

**Comment by NoSuck** [comment]
Fira Sans does not contain the Chinese characters you wish to display.  The reason they showed up in Firefox is because Firefox fell back to an alternative bitmap font... Qutebrowser also falls back to alternative fonts, but perhaps Qt WebKit does not like bitmap fonts.  Try installing an OpenType or TrueType font and see what happens.  [The IPA fonts](http://ipafont.ipa.go.jp/ IPA fonts) are good for both Japanese and Chinese.

**Comment by cwmke** [comment]
That did the trick @NoSuck.  Thanks a lot and sorry for the trouble.
