### ISSUE TITLE
Fall back to www.* if non-www-domain is unresolvable

### ISSUE THREAD

**Issue by sudo-nice** [The-Compiler/qutebrowser#1198]
Just try to open these urls: http://linux-kvm.org and http://www.linux-kvm.org

**Comment by The-Compiler** [comment]
I don't follow. http://linux-kvm.org doesn't work (because it doesn't have an `A`/`AAAA` record in the DNS), but I see the same behaviour with e.g. Chromium. This is something the website owner should fix.

Are you saying qutebrowser should act like Firefox here, and try resolving `www.linux-kvm.org` if `linux-kvm.org` doesn't resolve?

**Comment by sudo-nice** [comment]
You're right, some browsers don't attempt to resolve urls without 'www', but it's a handy feature.

**Comment by The-Compiler** [comment]
I'm going to say no to this one, sorry - after some more thinking about it, it's just too brittle to implement in a clean way.
