### ISSUE TITLE
userscripts: play_in_mpv wrong url because $QUTE_URL is overwriten by javascript

### ISSUE THREAD

**Issue by rumpelsepp** [The-Compiler/qutebrowser#1199]
The issue is about this script: https://github.com/The-Compiler/qutebrowser/blob/master/misc/userscripts/view_in_mpv

`$QUTE_URL` is overwritten after the javascript is executed and the userscript fails with exit code 2. The fix is very simple and I am to lazy to do the github fork/pull request stuff for this trivial thing; here is a patch which fixes that problem.

```patch
From f441691b50fde0e0ca4669353f09c6e0de51bbc3 Mon Sep 17 00:00:00 2001
From: Stefan Tatschner <rumpelsepp@sevenbyte.org>
Date: Tue, 29 Dec 2015 19:50:35 +0100
Subject: [PATCH] misc/userscripts: Do not overwrite $QUTE_URL

This patch fixes a problem in a provided userscript. The variable
$QUTE_URL is overwritten *after* executing the javascript code, thus
spawning mpv fails. This patch stores the video url in advance in
$VIDEO_URL to avoid failing painfully.
---
 misc/userscripts/view_in_mpv | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/misc/userscripts/view_in_mpv b/misc/userscripts/view_in_mpv
index 51aee47..b063b79 100755
--- a/misc/userscripts/view_in_mpv
+++ b/misc/userscripts/view_in_mpv
@@ -49,6 +49,9 @@ MPV_COMMAND=${MPV_COMMAND:-mpv}
 # Warning: spaces in single flags are not supported
 MPV_FLAGS=${MPV_FLAGS:- --force-window --no-terminal --keep-open=yes --ytdl }
 video_command=( "$MPV_COMMAND"  $MPV_FLAGS )
+# When the javascript below is executed,$QUTE_URL is overwritten.
+# Let's store the value in a separate variable.
+VIDEO_URL=$QUTE_URL

 js() {
 cat <<EOF
@@ -137,5 +140,5 @@ printjs() {
 }
 echo "jseval -q $(printjs)" >> "$QUTE_FIFO"

-msg info "Opening $QUTE_URL with mpv"
-"${video_command[@]}" "$QUTE_URL"
+msg info "Opening $VIDEO_URL with mpv"
+"${video_command[@]}" "$VIDEO_URL"
--
2.6.4
```

**Comment by t-wissmann** [comment]
Nice to see a patch with a perfectly formatted commit message :+1:

Can you give an example url where this happens? Because in principle, only `view_in_mpv` can change  `$QUTE_URL`, see http://stackoverflow.com/questions/205064/is-there-a-way-to-change-another-processs-environment-variables (Or does qutebrowser do something like this gdb-hack, @The-Compiler ?). In short: If process A spawns process B (via fork&exec), then B obtians a copy of the environment of A. Even if A changes some environment variable, then it stays unchanged in B. So I don't see where `$QUTE_URL` is changed by/after evaluating the javascript.

In the case of `view_in_mpv`, you can see that `$QUTE_URL` is not changed, since it is printed in qutebrowser's statusline by the second last line of the script.

So I guess the problem is caused by something different.

**Comment by rumpelsepp** [comment]
I have discovered qutebrowser yesterday, so I have not digged deep into it. The problem is just that appearently the javescript overlay causes qutebrowser to remove the videoid part and the link looks like this `https://youtube.com` rather than this `https://youtube.com/watch?v=lflksajfsakjd`. The lack of the video causes mpv to fail. Storing the link away *before* generating the js overlay fixes that problem.

**Comment by The-Compiler** [comment]
@t-wissmann qutebrowser just uses Qt's [QProcess](http://doc.qt.io/qt-5/qprocess.html)/[QProcessEnvironment](http://doc.qt.io/qt-5/qprocessenvironment.html) - I don't think that does any weird stuff, but I don't actually know :wink:

I'll take a closer look at this later, I'd like to understand what's happening before merging the fix.

**Comment by t-wissmann** [comment]
Firstly, the javascript overlay certainly does not remove the videoid-part of the url. Just try it, or tell us a url, where this happens. And secoundly, even if it did, this would not change the value of `$QUTE_URL`, for the reasons mentioned above.

I guess, the actual problem is following: sometimes, if one clicks on youtube, the video is directly shown without changing the url. So if one runs `view_in_mpv` after that, the video from the url is shown in mpv and not the video that is currently displayed in the webpage. In such a situation, one might think that there is a bug in `view_in_mpv` (but of course it's not).

@rumpelsepp, please tell me an example URL, where view_in_mpv fails. It works fine on youtube, see https://cloud.githubusercontent.com/assets/9048813/9633251/24a25254-518c-11e5-897f-01ec3f6aac0c.gif for a demonstration and observe how the get-parameters aren't droped in the notification text in the statusbar.

Thanks @The-Compiler, QProcess is surely just a wrapper around fork&exec and certainly won't try to change environment variables of children using gdb-tricks. :-)

**Comment by rumpelsepp** [comment]
@t-wissmann: Thanks for your explanation! I will have a look at yout link these days, but maybe in 2016 because everybody goes crazy these days and I have not that much time. :-)

**Comment by t-wissmann** [comment]
The "it works fine for youtube"-link is just a 10 seconds video :-)

**Comment by The-Compiler** [comment]
I agree with @t-wissmann - qutebrowser doesn't (and couldn't possibly, without evil hacks) change `$QUTE_URL` after the script has been invoked.

I'm guessing you're running into #870 which I've seen happen on youtube as well. 

Unfortunately I don't know of a good way to reproduce it, which also explains why it probably looked like it worked after your patch :wink:
