### ISSUE TITLE
ignore documentation for code coverage

### ISSUE THREAD

**Issue by mschilli87** [The-Compiler/qutebrowser#1202]
Commit 61ab3cf changes only [INSTALL.asciidoc](https://github.com/The-Compiler/qutebrowser/blob/master/INSTALL.asciidoc).
Still it is reported to decrease the code coverage by @codecov-io in pull request #1201.
I think documentation files that will never be executed by the tests should be ignored as described in the [coverage-documentation](https://github.com/The-Compiler/qutebrowser/blob/master/INSTALL.asciidoc).

**Comment by The-Compiler** [comment]
I've noticed the same issue and tried to debug it with @stevepeak some weeks ago.

One problem is that some code paths are non-deterministic (i.e. sometimes one and sometimes another path is taken because of race conditions), so the coverage is non-deterministic as well - when you look at the comment, the changed line numbers don't line up with the lines you changed, so it's not an issue about the documentation being ignored.

I disabled the comments for now (I hope - it's not obvious how to completely disable them).
