### ISSUE TITLE
Saving pdf from pdf.js fails due to "filename too long"

### ISSUE THREAD

**Issue by glspisso** [The-Compiler/qutebrowser#1214]
When opening and then downloading some pdf in qute with pdf.js the download fails reporting "Filename too long". The filename appears in red on top as a long list of gibberish. Note, that is not the name of the pdf one would expect. See for an example :
http://www2.warwick.ac.uk/fac/sci/mathsys/courses/msc/ma933/resources/ma933_15_handout1.pdf

This is the first time this happened to me, for other pdfs the download button worked as expected.

Workaround suggested by dunj3, simply use :download while viewing the pdf in qute. Works for me.

**Comment by Kingdread** [comment]
The problem/cause is as follows:

To download a PDF file, pdf.js generates a data url via javascript, embeds it and simulates a click. This URL looks like `data:;base64,Zm9vYmFy`, and it contains the whole PDF file encoded as [base64](https://en.wikipedia.org/wiki/Base64) - those are the "random" characters and explains why the filename is so long.

That's not an issue in itself, but when providing no filename, qute defaults to using the last part of the URL as the filename (so when you download `example.com/foo/bar.html`, the filename is `bar.html`), so in this case, the suggested filename is the whole long PDF, encoded as base64.

pdf.js tries to prevent this by setting the [`download` attribute](https://developer.mozilla.org/en/docs/Web/HTML/Element/a#Attributes) on the link to the PDF filename, but this attribute doesn't seem to affect qute in its choice of a filename (the filename information is unavailable to the download manager). *(FWIW: Chromium also doesn't honor the `download` attribute)*

As another workaround (besides using `:download` instead of the download button), I've changed the logic slightly when encountering `data:` links, though I'm not sure if this fix/workaround should/will be included in qutebrowser:

```diff
diff --git a/qutebrowser/browser/downloads.py b/qutebrowser/browser/downloads.py
index 448ab12..c912e51 100644
--- a/qutebrowser/browser/downloads.py
+++ b/qutebrowser/browser/downloads.py
@@ -774,7 +774,26 @@ class DownloadManager(QAbstractListModel):
         # https://bugreports.qt.io/browse/QTBUG-42757
         request.setAttribute(QNetworkRequest.CacheLoadControlAttribute,
                              QNetworkRequest.AlwaysNetwork)
-        suggested_fn = urlutils.filename_from_url(request.url())
+        if request.url().scheme().lower() != 'data':
+            suggested_fn = urlutils.filename_from_url(request.url())
+        else:
+            # We might be downloading a binary blob embedded on a page or even
+            # generated dynamically via javascript. We try to figure out a more
+            # sensible name than the base64 content of the data.
+            origin = request.originatingObject()
+            try:
+                origin_url = origin.url()
+            except AttributeError:
+                # Raised either if origin is None or some object that doesn't
+                # have its own url. We're probably fine with a default fallback
+                # then.
+                suggested_fn = 'binary blob'
+            else:
+                # Use the originating URL as a base for the filename (works
+                # e.g. for pdf.js), but does not eliminate the bug completely,
+                # as download attributes are still ignored.
+                suggested_fn = urlutils.filename_from_url(origin_url)
+
 
         # We won't need a question if a filename or fileobj is already given
         if fileobj is None and filename is None:
```

**Comment by The-Compiler** [comment]
I've had similar issues when downloading from mega.co.nz.

http://caniuse.com/#feat=download says it's supported in Chromium, and indeed it seems to work fine there.

**Comment by Kingdread** [comment]
As far as I can see, Chromium forces the download, but doesn't use the filename, as you can try with

```html
<html>
<body>
<a href="http://qutebrowser.org/index.html" download="qutebrowser.html">Foo</a>
</body>
</html>
```

\- so Chromium seems to at least have a better fallback mechanism for `data:` links.

I'd guess mega.co.nz uses a similar technique like pdf.js (as they use this advanced downloading thingy), so the same issue applies there (though I haven't checked the source).

**Comment by pkmarkosarnych** [comment]
I suggest to use a third party tool in this case. I always use Long Path Tool to bypass long path errors

**Comment by The-Compiler** [comment]
@pkmarkosarnych Hi! Is this somehow related to this issue or are you just a spambot? :wink:

**Comment by pkmarkosarnych** [comment]
I don't know if it will help you but i always use this kind of tool to bypass long path errors. Give a shot and tell me your experience

**Comment by The-Compiler** [comment]
Let's use this solution until we maybe find out about a better one :wink:
