### ISSUE TITLE
Mac launcher 

### ISSUE THREAD

**Issue by Promises** [The-Compiler/qutebrowser#1224]
Launching the browser in osx is a pain, could you supply some launcher for it?

**Comment by The-Compiler** [comment]
The best solution for this would probably be to build a proper `.dmg`/`.app`, like outlined in #384.

I tried that last April and had various strange trouble with segfaults and whatnot, so I moved on. I'm not a Mac user myself, and only have access to a Mac for a few hours a week, so this really isn't a priority for me I'm afraid.

If you feel like playing with `cx_Freeze` (the thing I use to generate Windows `.exe`s and which can also generate `.app`/`.dmg`), please do and let me know how things work!

Otherwise, you can probably write a `.command` file which launches qutebrowser and add that to your dock, but I never tried that.

**Comment by The-Compiler** [comment]
FWIW, I did a quick test with @flv0 today, and it seems it's even more broken than it used to be - see https://github.com/The-Compiler/qutebrowser/issues/384#issuecomment-171435139
