### ISSUE TITLE
QXcbClipboard: SelectionRequest too old

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1287]
I'm seeing a lot of these warnings when I select text using a mouse:
```
WARNING: QXcbClipboard: SelectionRequest too old
  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.5.1', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 153, in main
    return app.run(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 111, in run
    ret = qt_mainloop()
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 121, in qt_mainloop
    return qApp.exec_()
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/log.py", line 353, in qt_message_handler
    stack = ''.join(traceback.format_stack())
```
Generally the faster I move the mouse during selection, the more warnings are generated. I've played with `watch -n 1 'echo "$(xclip -o)"'` in terminal and the problem seems to be that QWebView updates the clipboard while the mouse moves, so maybe the warning is a result of some events being processed in wrong order. An optimization that should work in most cases would be to emit the selection request only once when the mouse button is released - other widgets do this, even qutebrowser's command line works like this. Is it possible to work around this in qutebrowser or is it Qt bug?

**Comment by The-Compiler** [comment]
FWIW I don't see this, on Qt 5.5.1.

I don't think I can work around it, but I can hide the warning (i.e. convert it to a debug message).

**Comment by The-Compiler** [comment]
Some questions after I researched this a bit:

- What Qt version are you on (`:open qute:version`)
- Are you copying latin chars or something else?
- Do you run some kind of clipboard manager, like Klipper?

Though I already ignored this message for tests because it sometimes showed up:
https://github.com/The-Compiler/qutebrowser/issues/1124#issuecomment-158073581

So I might as well ignore it globally, it's more that I'm curious what's causing it.

**Comment by lahwaacz** [comment]
I'm sorry for not providing the version info right in the first post. Basically, I'm also on Qt 5.5.1 (in Arch), with no desktop environment (only i3) and no clipboard manager.
(The commit is from lahwaacz/qutebrowser@22ad051, the changes are unrelated to clipboard. FWIW, other Qt5 browsers behave the same.)
```
qutebrowser v0.5.1
Git commit: v0.5.0-342-g22ad051 (2016-02-04 09:43:31 +0100)

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1
Style: QFusionStyle
Desktop: None
sip: 4.16.9
colorlog: yes
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1
yaml: 3.11
cssutils: no
pdf.js: 1.2.109 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2f  28 Jan 2016

Frozen: False
Platform: Linux-4.4.1-2-ARCH-x86_64-with-arch, 64bit
OS Version: 
```
Although it is not a big problem for me, emiting selection requests while the mouse moves also means noticeable increase on system load, which won't be helped by hiding the message. I'm really curious to know what's causing this.

It also does not seem to be specific to certain locale - it happens even when I select any paragraph on this very page.

**Comment by The-Compiler** [comment]
I see - unfortunately I'm not going to fix this in Qt myself, and since Qt is deprecated, it's unlikely anybody will care if you report it upstream. So hiding the message is the best I can do at the moment, really.

It'd be interesting to see if it happens with QtWebEngine, if you're on a distribution which packages it. Can you try with `python3 scripts/minimal_webkit_testbrowser.py http://www.qutebrowser.org/` (you should see the warnings) and the same with `--webengine` (they should hopefully be gone)?

**Comment by lahwaacz** [comment]
They are still there, even in QtWebEngine :disappointed:

**Comment by The-Compiler** [comment]
Well, that means at least there's a chance Qt upstream will take a look at it :wink:

I suggest you try reproducing it with a normal Qt widget (to confirm it's really not showing up there), then reproducing it with the QtWebEngine demo browser (part of qt5-examples in the AUR if you're on Arch), and then reporting it upstream: https://bugreports.qt.io/

**Comment by The-Compiler** [comment]
I added the message to the ignored warnings now.
