### ISSUE TITLE
SVGs doesn't show up

### ISSUE THREAD

**Issue by ndalliard** [The-Compiler/qutebrowser#1303]
When I go to [nate.do](https://www.nate.do/) and click on the plus sign, the SVG images aren't displayed.
In Chromium they are shown properly.

Hast it something to do with this user agent stylesheet rules:
![2016-02-13-152135_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/13028126/d651e578-d265-11e5-90f3-110bcde99f41.png)

Funny is, that some times they are displayed. But mostly they are not. Can't recreate this.

Any ideas? Problem on qutebrowsers side?

**Comment by The-Compiler** [comment]
No idea what's causing this I'm afraid, but I can reproduce it with other QtWebKit based browsers, so it seems like this is a QtWebKit issue.

Unfortunately QtWebKit is deprecated upstream, so reporting this bug upstream probably won't help much either...

This will probably be fixed in the future with the new QtWebEngine/Chromium backend (#666) though.
