### ISSUE TITLE
Smooth scrolling does not work with ^U and ^D

### ISSUE THREAD

**Issue by mark-otaris** [The-Compiler/qutebrowser#1373]
When ui.smooth-scrolling is set to true, smooth scrolling works for ^B, ^F, j, k, PgUp, PgDn and the up and down arrow keys, but not for ^U and ^D (which are supposed to go up and down half a page, while ^B and ^F go up and down a full page).

**Comment by mark-otaris** [comment]
Smooth scrolling works with `:scroll-page 0 1`, `:scroll-page 0 -1` and `:scroll-page 0 2`, but not with `:scroll-page 0 0.5` or `:scroll-page 0 1.5`. It seems smooth scrolling simply doesn't work when scrolling a non-integer number of pages?

**Comment by The-Compiler** [comment]
QtWebKit does not do smooth scrolling for some reason when the API is used for scrolling. Since that also causes some other issues (no scrolling with multiple scrollable divs), `:scroll-page` actually emulates a pagedown-press when the number of pages is an integer, and uses the API otherwise.

Unfortunately, I can't do much about this, and upstream QtWebkit probably won't care - sorry!
