### ISSUE TITLE
Qutebrowser does not register itself as a valid handler for http/https protocols on Windows

### ISSUE THREAD

**Issue by craftyguy** [The-Compiler/qutebrowser#1382]
On Windows 8.1, Qutebrowser does not show up in the list of valid handlers for http and https protocols in the "set associations" window of the Control Panel. Other installed browsers (IE, Chrome, Firefox) all show up as valid handlers when I try to change the handler for these protocols.

Unfortunately I'm really not familiar with out an application advertises itself as a valid handler to Windows (and unfortunately I have to use Windows for work!), but please let me know if I can collect more information for you!

**Comment by The-Compiler** [comment]
See #22 - unfortunately setting a default browser is a major pain on every platform, which is why I never looked at it so far :laughing:

**Comment by craftyguy** [comment]
Actually, I wasn't filing this so that qutebrowser would try to make itself the default, but rather so that the installer would register qutebrowser as a valid protocol handler for HTTP & HTTPS, so that users could then make it the default for these protocols using the wacky ways Windows provides. Ultimately, it's impossible at the moment to make qutebrowser the default for these protocols because Windows does not think it's a valid handler.

This MSDN page has some info on how an application registers as a protocol handler: https://msdn.microsoft.com/en-us/library/windows/desktop/bb266527(v=vs.85).aspx#Inst_Reg

If I were more familiar with how you are creating the MSI, I might take a stab at fixing this :)

**Comment by The-Compiler** [comment]
I simply use [cx_Freeze](http://cx-freeze.readthedocs.org/en/latest/overview.html) which doesn't really allow to configure the installer in any way.

I however plan to switch to [PyInstaller](http://www.pyinstaller.org/) once I get it working with PyQt on Windows, because cx_Freeze is not maintained very well and breaks all the time.

Despite its name, PyInstaller has no way to do an installer, so I'll probably use [NSIS](http://nsis.sourceforge.net/Main_Page) or so for that.

**Comment by craftyguy** [comment]
Looks like NSIS supports registering the app as a handler for a protocol. The Pidgin NSIS installer script has an example of this... http://nsis.sourceforge.net/Pidgin
