### ISSUE TITLE
Restore a session in a separate instance

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1415]
Continuing https://github.com/The-Compiler/qutebrowser/issues/499#issuecomment-207596718, how can I restore a session in a separate instance? The behaviour of `--restore` in qutebrowser is fundamentally different from that of [dwb](http://portix.bitbucket.org/dwb/resources/manpage.html), which always starts a new instance. The `--basedir` flag is not useful here because the sessions storage (`~/.local/share/qutebrowser/sessions/` by default) is affected by `--basedir`.

To take it more generally, I don't think that mixing sessions in a single instance is a good idea. One thing is performance (the more separate processes the better), second is that `:q` affects the whole session and there is no `:session-close`. When `:session-load`, you have two sessions mixed together, each possibly involving multiple windows, without any way to separate them at this point. And the original session might have been accidentally unsaved.

**Comment by The-Compiler** [comment]
The behaviour of dwb is different even without sessions involved, as it simply starts one instance per window (e.g. even `:winopen` actually opens a new instance).

This seems to work because WebKitGTK seems to provide the means to do so - unfortunately QtWebKit (and quite possibly also QtWebEngine) doesn't, so qutebrowser has to use one instance for multiple windows, and can only have another instance with a completely separate cache/local storage/cookie/... store. It might be possible to share the config across instances (especially after the config revolution™), but probably not any other data.

---

> One thing is performance (the more separate processes the better)

QtWebEngine will have a renderer process for each tab, FWIW.

> second is that `:q` affects the whole session and there is no `:session-close`.

I think it's a good idea to add `:session-close`, and maybe even (optionally) indicating what session a window belongs to in the title. There is some previous discussion about this in #572, so I think this can be closed as a duplicate if you agree?

**Comment by lahwaacz** [comment]
I guess I'd be fine with per-window sessions (definitely more usable than what we have now), so yeah, closing.
