### ISSUE TITLE
No monospace font in source-view

### ISSUE THREAD

**Issue by rumpelsepp** [The-Compiler/qutebrowser#1451]
Hi;

when i view the source of a webpage, I don't have any monospace fonts any more. I deleted `.config/qutebrowser` to reset the settings to default, but nothing changed.

![screenshot-2016-04-25-10 18 06](https://cloud.githubusercontent.com/assets/1961699/14777731/439a8058-0acf-11e6-86c3-d610cfc98226.png)

The github raw view of a file, also does not use monospace fonts. What's wrong, is it a bug?

**Comment by The-Compiler** [comment]
@cym13 also reported this in #1432. It seems this is an issue introduced with Qt 5.6, which I think had quite a few font selection/rendering changes.

I hope it'll be fixed with 5.6.1, but I won't bother reporting it upstream I'm afraid, as QtWebKit is deprecated.

In other words: QtWebEngine will solve all of your problems(tm) :wink:

**Comment by rumpelsepp** [comment]
Ah, sorry for the dup...

> In other words: QtWebEngine will solve all of your problems(tm) :wink:

That's why I donated to the foundraiser. :D

**Comment by The-Compiler** [comment]
No worries! On a second thought I might be able to add a workaround for this (by doing *something* to the sourcecode CSS generated by Pygments), but it works fine for me...

> That's why I donated to the foundraiser. :D

Thank you!

**Comment by oatberry** [comment]
@rumpelsepp try this: `:set fonts web-family-fixed <mono-font-of-choice>`
