### ISSUE TITLE
Queue pop-ups and alerts

### ISSUE THREAD

**Issue by NoctuaNivalis** [The-Compiler/qutebrowser#1465]
I'm not sure how it works for other pop-ups and alerts, but the `ssl-strict: ask`-questions interrupt for instance an open `:quickmark-load` interaction. This is quite annoying, especially when one is about to hit a `y` in the quickmark. It'd be cleaner if the alert and ssl-strict questions were asked after the previous interaction is finished.

**Comment by The-Compiler** [comment]
Unfortunately that's not possible (or at least very hard to get right), as the SSL question is actually a blocking function called by Qt (i.e. I need to return a value) with a local event loop. This is why I want to ask the question and get out of the loop as fast as possible, otherwise things begin to interact in funny ways unfortunately...
