### ISSUE TITLE
Font fallback with fontconfig

### ISSUE THREAD

**Issue by terlar** [The-Compiler/qutebrowser#1481]
I am not sure if this is the correct place to raise this issue, since most browsers seem to have this issue and also that the backend will be switched out soon.

But it would be awesome if my favorite browser could handle this.

So it seems that if a glyph is missing in the specified font and there are several fallback fonts specified in fontconfig it instead fallbacks to the generic fallback font (in my case the `sans-serif` stack) or continues in the specification of fonts in the stylesheet.

So for example if I configure fontconfig like this (`~/.config/fontconfig/fonts.conf`):
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
<alias>
	<family>serif</family>
	<prefer>
		<family>Merriweather</family>
		<family>cwTeXMing</family>
		<family>Symbola</family>
	</prefer>
</alias>
</fontconfig>
```

And then I have an HTML page containing the font specification `serif`:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body style="font-family: serif;">
  <p>a b c d e f g h i j k l m n o p q r s t u v w x y z</p>
  <p>你好，一二三四五</p>
  <p>☺ 🙇</p>
</body>
</html>
```

So then it will first check if Merriweather includes the glyph, if it does, it will render it. However if the glyph was not found instead of continuing with the next font cwTeXMing it counts as a miss and fallsback to whatever font I have specified as my default font.

If you would try to run this with for example:
`pango-view --font=serif -t 'a b c, 你好'` it would work properly.

Or `fc-match -s serif | head`:

```
Merriweather-Regular.ttf: "Merriweather" "Regular"
Merriweather-Bold.ttf: "Merriweather" "Bold"
Merriweather-Italic.ttf: "Merriweather" "Italic"
cwTeXMing-zhonly.ttf: "cwTeXMing" "Medium"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
DejaVuSerif.ttf: "DejaVu Serif" "Book"
DejaVuSerif-Bold.ttf: "DejaVu Serif" "Bold"
DejaVuSerif-Italic.ttf: "DejaVu Serif" "Italic"
DejaVuSerif-BoldItalic.ttf: "DejaVu Serif" "Bold Italic"
SourceSerifPro-Regular.ttf: "Source Serif Pro" "Regular"
```

I just wonder what is responsible for this behaviour, is it out of scope for qutebrowser to handle this?

**Comment by The-Compiler** [comment]
Yeah, this is definitely something which would need to be fixed in Qt.

There are [numerous bugs open](https://bugreports.qt.io/browse/QTBUG-51417?jql=component%20%3D%20%22GUI%3A%20Font%20handling%22%20AND%20text%20~%20%22fontconfig%22) about bad fontconfig support. I'm not sure if this is a problem in Qt in general or QtWebKit - if it's the latter, chances this will be fixed in Qt are quite close to zero.

However QtWebEngine uses Chromium's graphic library ([Skia](https://skia.org/)) to do the font rendering - so if things look right in Chromium/Chrome, chances are they'll look properly in qutebrowser with QtWebEngine too.
