### ISSUE TITLE
Decode %-ed cyrillic letters in URL

### ISSUE THREAD

**Issue by code-hunger** [The-Compiler/qutebrowser#1483]
If you search for `абвг` and the do `go`, you'll get the URL with the cyrillic letters encoded, i.e. `%D0%B0%D0%B1%D0%B2%D0%B3`, which is quite unpleasant both to read and edit.
The same applies when hovering links with cyrillic letters in their url.  
It'd be nice if this can be fixed.

**Comment by The-Compiler** [comment]
Hmm, I thought you could do `:bind -f go set-cmd-text :open {url:pretty}` to get that behavior with `go`, but that seems to result in a literal `{url:pretty}` - do you have an idea why, @forkbong?

As for hovering URLs, Qt provides the URL as a string for reasons I don't know, but I guess qutebrowser could attempt to parse and decode the URL.

**Comment by forkbong** [comment]
It seems that [`set_cmd_text_command()`](https://github.com/The-Compiler/qutebrowser/blob/a5f2ac5f031fb12691ab447679462fa2b8bf69ce/qutebrowser/mainwindow/statusbar/command.py#L95) does its own substitutions instead of calling `replace_variables()`. 

Splitting with `shlex.split()`, calling `replace_variables()` and then rejoining should work and it would also solve #123. In which case do you think trailing spaces are a concern?

**Comment by The-Compiler** [comment]
I'll add a comment in #123.

**Comment by The-Compiler** [comment]
You can now use `{url:pretty}` to get that behaviour for `go`. I changed the default bindings, but with an existing config you'll need to run the `:bind` command above to get the new behaviour.

#1497 will also decode hovered URLs and hopefully be merged soon.

**Comment by The-Compiler** [comment]
#1497 was now merged, so you'll now see the decoded URL in the statusbar too.
