### ISSUE TITLE
"Home" on website does not work on sub-pages

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1489]
e.g. "home" on http://qutebrowser.org/doc/quickstart.html is a 404

cc @meles5

**Comment by forkbong** [comment]
The problem here is that the links in the header are relative to the current file, and if the current file is in `/doc`, the files can't be found.

The obvious ways to solve this is either moving everything to the root, or making links absolute like that:

```diff
 <div id="headline">
-	<img class="qutebrowser-logo" src="icons/qutebrowser.svg" alt="qutebrowser" />
+	<img class="qutebrowser-logo" src="/icons/qutebrowser.svg" alt="qutebrowser" />
 	<div class="text">
 		<h1>qutebrowser</h1>
 		A keyboard-driven browser.
 	</div>
 </div>
 <div id="menu">
-	<a href="index.html">Home</a>
-	<a href="FAQ.html">FAQ</a>
-	<a href="INSTALL.html">Install</a>
-	<a href="CHANGELOG.html">Changelog</a>
-	<a href="CONTRIBUTING.html">Contributing</a>
+	<a href="/index.html">Home</a>
+	<a href="/FAQ.html">FAQ</a>
+	<a href="/INSTALL.html">Install</a>
+	<a href="/CHANGELOG.html">Changelog</a>
+	<a href="/CONTRIBUTING.html">Contributing</a>
 	<a href="https://www.github.com/The-Compiler/qutebrowser">GitHub</a>
 	<a href="https://github.com/The-Compiler/qutebrowser/releases">Releases</a>
 	<a href="http://blog.qutebrowser.org/">Blog</a>
```

I'd choose the later, but it will work only if there is a server serving the website.  If you generate the website and have it locally in a folder, the links will point to the root of your filesystem.

This would also solve #1265.

**Comment by The-Compiler** [comment]
@forkbong Now I wonder why I didn't think of that :laughing: Thanks, fixed and deployed!
