### ISSUE TITLE
Logo is rather similar to Quickbooks

### ISSUE THREAD

**Issue by bb010g** [The-Compiler/qutebrowser#1528]
![Intuit Quickbooks logo](https://upload.wikimedia.org/wikipedia/en/e/e5/Quickbooks_intuit_logo.png)

I don't like to think that Intuit would bug a FOSS web browser about this sort of thing, but it's close enough to make me uncomfortable. I suppose all this means right now is to be open to new logo suggestions.

**Comment by ff2000** [comment]
On Tue, 24 May 2016 19:35:10 -0700, Brayden <notifications@github.com> wrote:
> ![Intuit Quickbooks logo](https://upload.wikimedia.org/wikipedia/en/e/e5/Quickbooks_intuit_logo.png)
> 
> I don't like to think that Intuit would bug a FOSS web browser about this sort of thing, but it's close enough to make me uncomfortable. I suppose all this means right now is to be open to new logo suggestions.

The similarities are
* the letters q and b
* letters are drawn symmetrical
* circle as background

They are different regarding
* font (qutebrowser does not use a real font, letters are "hand-drawn")
* alignment of the letters
* colors/background

As modern icons often use a circle as background this similarity can be ignored.
Both share the same abbreviation. And the letters q and b will result in a symmetric
figure in most fonts you chose. So redesigning qutebrowser logo will again result in
a similar icon.

IMHO the qutebrowser logo is different (as in not similar enough), but I'm not a
lawyer, this is simply my opinion.

**Comment by The-Compiler** [comment]
I appreciate you bringing this up, but I agree with @ff2000 - if you have a logo with letters in it for something abbreviated "qb", it's just going to have those letters in it :wink:

I also think it's different enough, and I'm not sure if any of the logo designers (WOFall who's not on GitHub afaik and @Xananax) have ever seen the quickbooks logo before, I didn't.

**Comment by Xananax** [comment]
I had not heard of Quickbook's logo, but if I had, it wouldn't have changed anything, as I consider the current logo far away enough in terms of shape, color, and feel.

Since I did not invent the logo, but just tweaked it a bit, I can allow myself to say that QuteBrowser's logo is imho much more original and has much more personality than Quickbooks', which is simply the letters Q and B in a circle. If you study the Qutebrowser logo, you'll notice subtle differences with a real font that allows the letters to flow into each other yet keep a visually balanced look. Keeping those two letters as close yet managing to fill the most possible space in the circle is no small feat. I know this because I've tried a lot of different combinations, but had to go back to the original designer's idea.

It's very different from just popping the two letters in a circle and calling it a day. Any designer worth his/her salt, regardless of personal preference, can't but say that much more thought and work has gone in the Qutebrowser logo (at least, as far as the icon is concerned). It therefore has a very different quality. I could go into details that explain why they are as different as can possibly be, but I don't really have the time right now. If you're not convinced, however, I can try to summarize the best I can, or answer specific questions.
