### ISSUE TITLE
Show completions for args with declared choices

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1532]
Now that `cmdutils.argument` is being used (c33f0c3512f21e6e906867d8909d0f83bd0b455e), there's some potential for expanding completions for commands.

After inputting `--someflag ` or `--someflag=` in the command bar, we could show completions if that flag has `choices`.

1. Is there already someone working on this?
2. Would it be a bad idea to do this before the proposed completion revamp in #74?

I threw together a really rough proof-of-concept in 6b2fb6629e407e3742363931ded752421f30e7fb

![file](https://cloud.githubusercontent.com/assets/2496231/15624581/11fa9990-2459-11e6-95b9-9e50ee9db6a7.png)

**Comment by The-Compiler** [comment]
Sorry for the delay - I think your proposed code is simple enough to include it before #74, and yay for more discoverability!

I think `:bind` is the only command which has a flag with an argument though, so it'd be nice if this would also work for positional arguments with choices (e.g. when doing `:navigate`) if it doesn't yet.

**Comment by rcorre** [comment]
> I think :bind is the only command which has a flag with an argument though, so it'd be nice if this would also work for positional arguments with choices

Yeah, that's part of the plan. I was thinking there'd be more flags with choices, but I guess not. I'd just been working with `bind` a lot recently so that was on my mind.
Completions for the flags themselves would be nice too. I'll poke around and see how much complexity that will add.

**Comment by The-Compiler** [comment]
> Completions for the flags themselves would be nice too. I'll poke around and see how much complexity that will add.

Yep, I already had that in mind in #32 some while ago :laughing: 

I think that'll be a lot harder, because at that point you need composable completions (since for every command, you can have *either* the completion for the argument, or flags), which basically is the goal of #74.

FWIW I'd also prefer minimal pull requests, makes things easier to review - so if you have something which seems ready and finished enough, feel free to open a PR and then another one when you improve things!

Also, would you be interested in working on that completion revamping (#74)? I don't really have a master plan in mind for that one, and it's unlikely I'll work on anything completion related in the near future - but at the same time I think it's a very important step towards getting more completions. If you think that'd be something you'd like to work on, would you mind [joining the IRC channel](https://github.com/The-Compiler/qutebrowser#getting-help) to talk about the details?

**Comment by rcorre** [comment]
Sounds good to me, I'm willing to try revamping completions. I'll jump on IRC, and we can talk about it some time.

**Comment by The-Compiler** [comment]
I added this to #32 to keep all completion ideas in one place.
