### ISSUE TITLE
KeyError in mhtml.finished

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1535]
Report on 0f8b298 without debug log and "`:download-cancel`" as report message:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/qutebrowser/browser/mhtml.py", line 357, in _finished
    self.pending_downloads.remove((url, item))
KeyError: (PyQt5.QtCore.QUrl('https://stribika.github.io/assets/nsa-happy-dance.png'), <qutebrowser.browser.downloads.DownloadItem basename='nsa-happy-dance.png'>)
```

Without cssutils installed FWIW.

@Kingdread want to take a look?

**Comment by The-Compiler** [comment]
I can reproduce this by doing `:download --mhtml ;; :later 2000 download-cancel` on this page.

**Comment by Kingdread** [comment]
`download.cancel()` emits both, `finished` and `cancelled`, which leads to both handlers being called, `_finished` and `_error`, and since `_error` is called before `_finished`, the download is removed from the list and `_finish` fails... which leads me to the question: If a download is cancelled, should it just use an empty file (like it does on error) or should it cancel the whole mhtml download?

**Comment by The-Compiler** [comment]
Hmm, good question... From an user's perspective I think both would be useful. Assuming an empty file if the user sees some big download but knows they don't need that one part, or cancelling the whole download if they accidentally download the wrong page or whatever.

Any other opinions? If not I'd say let's just assume an empty file because it's probably easier to implement :wink:

**Comment by Kingdread** [comment]
Cancelling the whole thing shouldn't be that difficult either, but the "disregard that single file" is probably useful, especially because there's no other mechanism for excluding elements.

On the other hand, we currently only download `img`/`link`/`script` elements (no `video` or something like that), so the amount of big files is probably pretty small.

**Comment by The-Compiler** [comment]
That's certainly what I'd expect, but you newer know with today's crazy weg
