### ISSUE TITLE
Fullscreen not working in standalone x Session

### ISSUE THREAD

**Issue by x421** [The-Compiler/qutebrowser#1546]
Just tried to run qutebrowser without a window manager/desktop environment and noticed that fullscreen is not working. :cry:

**Comment by lahwaacz** [comment]
Quite obviously, since you need a window manager to manage windows. If you try other browsers, it does not work either.

**Comment by x421** [comment]
Fullscreen modes in firefox and emacs are working fine for me using this way.

**Comment by The-Compiler** [comment]
So this seems to work in emacs, but with Firefox it doesn't change the window size, it just hides UI elements.

qutebrowser doesn't hide them since they don't take up much space anyways, it only changes the windows size. I agree with @lahwaacz that that is the duty of the window manager, not sure why it happens to work in emacs.

If you disagree, you'd have to open a [Qt bug](https://bugreports.qt.io/) and see what they think about it, as all qutebrowser does is to tell Qt to please turn on fullscreen.

**Comment by x421** [comment]
Thank you for the feedback.

I worked around with a xdotool script by the way.
