### ISSUE TITLE
Add :rl-backward-kill-word

### ISSUE THREAD

**Issue by SirCmpwn** [The-Compiler/qutebrowser#1698]
Previously, you could use ^W in the download prompt to delete the previous word, which was useful for backing up a single directory. Now it deletes everything up to the /.

---

qutebrowser v0.8.0
Git commit: 

CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.2.109 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Platform: Linux-4.6.4-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Desktop: None
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

--- /etc/arch-release ---
Arch Linux release

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

**Comment by The-Compiler** [comment]
Yeah, the behaviour changed to match what readline does. You can use `Ctrl-Backspace` FWIW, but it might make sense to override this for (download?) prompts.

cc @edi9999 who did that in #1592.

**Comment by lahwaacz** [comment]
Well, readline is customizable via `inputrc`, so the right way to do this is via [readline](https://docs.python.org/3.5/library/readline.html) or similar interface which does not block and provides the completion callbacks.

**Comment by edi9999** [comment]
Hey, yes indeed, I wanted to respect readline a bit more by having C-W delete one full argument (that's what readline does by default with C-W). 

I think in readline, to delete a word, the shortcut is `Alt-backspace`, but in qutebrowser it is `Ctrl-Backspace`.

> but it might make sense to override this for (download?) prompts.

I would find it very confusing if the shortcuts were behaving differently depending on the type of prompt. I think `C-w` might also make sense in the download section, since you maybe want to save your file to /tmp/foo.txt for example, in which case it is fastest to start from an empty string.

> the right way to do this is via readline

I would also like to have a "real" readline implementation, but I'm not sure readline is "input" agnostic, eg how can you make it work from inside Qt (Usually readline is used with console AFAICT) ?

**Comment by The-Compiler** [comment]
Using a real readline implementation is an interesting idea, but I think it has some drawbacks - I think the implementation might get quite complicated, and it's not available on Windows.

pyreadline seemed interesting, but it seems to just expose the same interface `readline` does? Also, it seems pretty much unmaintained, and not commonly packaged.

But back to this issue - I think `Ctrl-Backspace` just works because it's a default Qt shortcut for input fields, not because qutebrowser does anything specific. I think we could simply add a `:rl-backward-kill-word` command (what `Alt-Backspace` is in readline) with the old behaviour, and then @SirCmpwn could simply rebind `C-w` to that?

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by edi9999** [comment]
Great !
