### ISSUE TITLE
Feature Request: Ctrl-Enter in open dialog surrounds entry with URL elements

### ISSUE THREAD

**Issue by madhat2r** [The-Compiler/qutebrowser#1749]
Work like all the browser address bars. if you type `google` and press `ctrl-enter` then it translates that into `http://www.google.com` and goes there.

**Comment by The-Compiler** [comment]
Since qutebrowser doesn't really have an address bar (only a command line), I don't really see a clean way to implement this. `Ctrl-Enter` would have to be bound to a special command which checks if the command is actually `:open`, adjusts the URL accordingly, etc.

I'm also not really convinced that it's useful (how many sites people visit are actually `.com`?), so I'm afraid I'll have to say no to this one - however I added it to #30 as a possible usecase for a future plugin API.

**Comment by lahwaacz** [comment]
@madhat2r This is exactly what plain `enter` does, assuming that `google` is a quickmark for `http://www.google.com`.

**Comment by madhat2r** [comment]
@The-Compiler fair enough. It was really just a muscle memory thing for me as I have been using it for years.

@lahwaacz good to know I have not really gotten around to configuring quickmarks yet, that will certainly be helpful.
