### ISSUE TITLE
Support for ICC profiles and color management

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1783]
As a user of a wide gamut monitor, color management is a must-have feature for me.

At the minimum, qutebrowser would need to support some mechanism for the user to specify what ICC profile to apply to the display. (Though if possible, it should also try and load these automatically from the corresponding X atoms)

I imagine WebKit already implements color management and ICC profile support internally, so this would probably be relatively easy to implement - but I could be wrong.

In addition to supporting user-specified ICC profiles for full-page color management, qutebrowser should also treat the display as sRGB by default (in the absence of any user configuration) and transform non-sRGB images to sRGB in the same way. This affects, for example, AdobeRGB-tagged photos being displayed on a stock browser.

You can use these websites to test the status of color management in qutebrowser:

* http://www.color.org/version4html.xalter
* http://www.gballard.net/psd/go_live_page_profile/embeddedJPEGprofiles.html

**Comment by The-Compiler** [comment]
There's nothing I can do about this, as it's something somewhere deep inside the rendering engines :wink: However, with the upcoming QtWebEngine backend (based on Chromium), the ICC v2 color profiles seem to work fine out of the box. You can test it with `--temp-basedir --backend webengine` with qt5-webengine installed, but many features will still be missing.

**Comment by lamarpavel** [comment]
Does QtWebEngine allow for any configuration? If so, maybe we should keep this issue open and come back to it once the backend-abstraction and implementation of QtWebEngine is done, because I think there is more to discuss here.
For example, should qutebrowser eventually support Servo as third backend, that might have vastly different capabilities for ICC profiles and it would be nice to keep that in mind and maybe allow for some configuration in qutebrowser itself.

Webdesigners/devs will find this useful as well, as they need to check how their pages look on different screens with different colour profiles and it would be neat to be able to toggle/cycle colour profile management.

**Comment by The-Compiler** [comment]
> Does QtWebEngine allow for any configuration?

Nothing I'm aware of. Do you know if Chromium does, even via commandline argument or an environment variable? If not, I doubt it would be something which could be added easily to QtWebbEngine upstream.

**Comment by lamarpavel** [comment]
Sorry no, I have not used chromium in many years and know very little about it.

**Comment by gavtroy** [comment]
Only half of this issue was fixed with webengine. The color profile information embedded into images is used now, but the monitor is still assumed to be sRGB. This leaves all images oversaturated on a WCG display. Assuming you've first used colormgr to attach a WCG profile to your monitor (any monitor can be used), you can test this here
https://cameratico.com/tools/web-browser-color-management-test/

Chrome:
![2019-11-10-151622_686x346_scrot](https://user-images.githubusercontent.com/3988605/68546348-2c9eb900-03cd-11ea-8657-78d5094939f4.png)

qutebrowser does not reduce the saturation in the bottom half. Neither does Otter.

I'll refrain from opening a new issue since this one was marked "nothing we can do". I assume that part hasn't changed.
