### ISSUE TITLE
Client-side sandboxed CPython with DOM support via <script type="text/python"> tag

### ISSUE THREAD

**Issue by ethana2** [The-Compiler/qutebrowser#1824]
Currently brython.js is only 1/15th the speed of CPython, and I'd like to be able to write my own web applications in both server- and client-side Python without that performance overhead and run them in my browser.

**Comment by The-Compiler** [comment]
This is not going to happen I'm afraid, for various reasons:

- Sandboxing CPython in a secure way is impossible - see e.g. [the pysandbox project is broken](https://mail.python.org/pipermail/python-dev/2013-November/130132.html) and [eval really is dangerous](http://nedbatchelder.com/blog/201206/eval_really_is_dangerous.html).
- This is hard to implement, even with sandboxing out of the equation (due to only having DOM access via JS). If anything, you'd only have a tiny subset of the DOM.
- The use cases are extremely limited, nothing except home-grown web applications of qutebrowser users will ever use this.

There are some projects which are a transpiler between a Python-subset and JS (similar to [Coffeescript](http://coffeescript.org/)). The ones I can remember from the top of my head are [Rapydscript-NG](https://github.com/kovidgoyal/rapydscript-ng) and [Transcrypt](http://www.transcrypt.org/)., but there are one or two more I think. Maybe that would be an alternative for you?
