### ISSUE TITLE
Undo after tab-detach reopens the detached tab

### ISSUE THREAD

**Issue by Enzime** [The-Compiler/qutebrowser#1827]
As `:tab-detach` currently closes the tab normally and then reopens it elsewhere, `:undo` will reopen the tab that was detached.

**Comment by haasn** [comment]
If this is implement then `:undo` should take a parameter, like `:undo close` or `:undo tab-dedetach` (the parameter being the command you would like to undo, or `:undo any` (default) for all).

Reason is because personally I don't think of ‘undo’ as ‘undo my last action’, I think of it as ‘undo close tab’.

**Comment by The-Compiler** [comment]
@haasn This is a bug report saying that `:undo` *does* kind-of-undo `:tab-detach` and it shouldn't.

**Comment by haasn** [comment]
Oh, I see :)
