### ISSUE TITLE
Display dialog boxes more prominently

### ISSUE THREAD

**Issue by B0073D** [The-Compiler/qutebrowser#1898]
I would like to be able to configure qutebrowser to display dialog boxes and other items requiring input to be displayed more prominently.

For example, SSL warnings and other things that often steal focus are currently displayed in the status bar at the bottom. A lot of the time I do not see these right away. Only when I wonder why the page is not loading do I see these.

A preferred method or option would be to display them in the center of the screen, perhaps in a 'Windows 10' style bar across the screen with the content grayed out?

I believe this would improve usability.

**Comment by The-Compiler** [comment]
Making them modal (i.e. not allowing the user to interact with the page while they're open) would also make the code a lot simpler, and is something which was in the back of my mind for a while already.

I think Otter Browser is a good example:

![js](https://cloud.githubusercontent.com/assets/625793/18041610/ed9ac952-6dba-11e6-845c-73ec79716788.png)

I imagine something similar, but of course with keyboard navigation in mind.

**Comment by The-Compiler** [comment]
Raising the priority of this as I hope it'd make it possible to get rid of a lot of complexity in the code.

**Comment by The-Compiler** [comment]
A small overview about what kind of prompts we have currently, classified according to these properties:

- Some of them are **sync**hronous, which means we need the answer for that question before the answer to any older synchronous questions. We also might want to consider making them application-modal to minimize the actions the user can do, which minimizes the possibility for edge-cases (crashes/hangs) of which there are a lot otherwise.
- Some of them are designed to be page **modal**, i.e. the page is blocked until they are answered
- Some of them are **global**, i.e. not associated with a specific tab or window
- Some of them are the result of a direct **prompt** input, so a full-tab dialog might be too intrusive?

The questions:

- Javascript alert: modal
- Javascript confirm: modal, sync
- Javascript prompt: modal, sync
- Feature permission: none
- SSL errors: modal?, sync
- HTTP authentication: modal?, sync
- Proxy authentication: modal, sync
- Download location / overwrite-confirm:
   - WebKit: origin
   - WebEngine: sync, global
- Quickmark name: prompt
- Quickmark override question: prompt
- "Open external application": modal
- Quit confirmation: modal, sync, global

Some considerations:

- Do we want per-tab questions instead of global ones? I think yes, as it makes it easier to see why something happens (e.g. where an SSL error originated from).
- If we do, what about synchronous questions? The best I could come up with is something like "The question in tab x needs to be answered before this one, use `:prompt-accept` (Enter) to go there".
- For the global one(s), we can probably just ask a window modal question in *every* window...
- Do we want a full-tab question thingy for a quickmark name? I'd say no, but then we'd need to keep the old code around too?
- Maybe don't have full-window questions at all, but definitely bigger than the statusbar (say, 100px or so), and have the page blurred/darkened?

**Comment by The-Compiler** [comment]
# Behavior/design in other browsers

## Chromium

Chromium uses floating dialog boxes over a given page:

![chromiumauth](https://cloud.githubusercontent.com/assets/625793/18686341/e50f8480-7f7b-11e6-8637-a982b57501d4.png)

![chromiumdialog](https://cloud.githubusercontent.com/assets/625793/18686358/eda6b7ee-7f7b-11e6-9a2a-c8092a27b777.png)

Those can be application modal and prevent switching of tabs, or they can allow it (like the auth dialog).

When tab switching is forbidden, the dialog has a slight shake/nudge when trying to do so. When doing anything in a different Chromium window, nothing happens and the blocked window sends an urgency hint.

For file path dialogs, a separate window is opened.

## Firefox

Firefox uses a dialog over a dimmed down page:

![firefoxdialog](https://cloud.githubusercontent.com/assets/625793/18686448/4083579c-7f7c-11e6-8575-d71b771b7344.png)

Those are never modal, but I guess that's just something Firefox/Gecko allows them to do internally.

# Other thoughts

Originally a Windows-like thing was mentioned:

![restartwin10](https://cloud.githubusercontent.com/assets/625793/18686498/6808040c-7f7c-11e6-8d02-65d413d1e1c6.jpg)

However I'd rather not have something which remembers people of Windows :laughing: 

For `:quickmark-save` where a full-screen dialog would be rather intrusive, couldn't we just bind that to something setting the command text to `:quickmark-add {url} ` instead? However that might be less intuitive, and what do we do for duplicates?

For selecting files/directories, can we show a dialog overlay like that with an input (like now) plus a graphical file picker?

**Comment by The-Compiler** [comment]
I think I'm going for something attached to the statusbar - first draft:

![auth](https://cloud.githubusercontent.com/assets/625793/18763118/2db4f8f0-810c-11e6-8332-fbc4073aa719.png)

For files, this might even include a file browser/list.

Not 100% sure how to handle modality and other constraints yet, and if prompts will be per-tab (i.e., hidden when you switch to another tab).

**Comment by The-Compiler** [comment]
I think the relevant keys should be shown for any messages, and I'm currently working on a complete rewrite of the prompts (see https://github.com/The-Compiler/qutebrowser/issues/1898#issuecomment-249005372) which does that (among other things), so I'm going to close this.

Thanks for the contribution though! :smile:

**Comment by The-Compiler** [comment]
Whoops, I failed at copy-paste :wink:
