### ISSUE TITLE
Completion for ":open a   b" hangs qutebrowser

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1919]
It seems we get longer hangs with more spaces, and it doesn't happen with `--temp-basedir`.

**Comment by Kingdread** [comment]
The issue seems to be [this line](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/completion/models/sortfilter.py#L72):

```python
 val = val.replace(r'\ ', r'.*')
```

With many spaces, we end up with a regex like `a.*.*.*.*.*.*b`. Now, when the match fails, the regex engine isn't smart enough to notice that backtracking isn't useful here, so it removes one character from the first `.*` match and assigns it to the second `.*`, repeating this process until every combination of `.*` group has been tried. I think we're running into some exponential-growing stuff here (but don't quote me on that).

The solution would probably be to collapse multiple spaces into one before transforming, to avoid unnecessary backtracking.

**Comment by Kingdread** [comment]
FWIW, the debugger at https://regex101.com/#python shows for the regex `a.*.*.*.*.*.*.*b` and the text `http://test.a/cdasdasdasd` 90823 steps until the match failed. Now imagine that for each URL that fails this pattern. The issue doesn't arise with `--temp-basedir` because there just aren't any entries to filter.

**Comment by The-Compiler** [comment]
Thanks for the debugging help, @Kingdread!

**Comment by The-Compiler** [comment]
Whoops, forgot to mention the issue in the commit message - this was fixed in faa052ad6f2b04afcf5bc8bb3d1481c8f74a5d6d.
