### ISSUE TITLE
Argument overload for commands

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1936]
We have various commands like `:set`, or `:repeat` after #725 (and probably more!) which have various valid "signatures" which differ significantly from each other. For example with `:set`:
- `:set` (opens `qute:settings`)
- `:set section option?` (shows a value)
- `:set [--temp] [--print] section option value` (sets a value)

We currently do this by having quite a "forgiving" signature for `:set`: `
:set [--temp] [--print] [section] [option] [value]` and then explaining the actual usage in a docstring.

With various possible command overloads, we could generate better signatures in the docs, and also make the command handlers much easier.

One problem I see is what error to display to the user though... If we just print the separate errors for each overload, the error message shown in the UI is going to look like C++ compiler messages...

**Comment by lahwaacz** [comment]
I think that using [sub-commands](https://docs.python.org/3/library/argparse.html#sub-commands) instead of overloading would be better, but that doesn't apply to `:set`. Argparse also has [mutually exclusive groups](https://docs.python.org/3/library/argparse.html#mutual-exclusion), which are only for optionals. Are there more cases like `:set`?

The signature of `:set` looks very similar to [sysctl](http://man7.org/linux/man-pages/man8/sysctl.8.html), which has this signature:

    sysctl [options] [variable[=value]] [...]

IIRC switching to the `section.option` categorization is also planned for qutebrowser? The other difference is the `?` which is useless regarding signature (but of course can be kept for backwards compatibility and vim-like feel). This would reduce to this signature: `:set [option] [variable[? | ! | =value]]`. Since `variable` and `value` are separated by `=` instead of a space, there is only one positional argument (possibly with `nargs='*'` specifier). Its help message can say that if no variable is specified, `qute:settings` is opened. Now there might be options that make sense only for setting values, but they can be simply ignored if the signature resolves to getting.

I don't know how you imagined the overloading to work, but this seems like a common problem which argparse should be able to handle the _classical_ way, even with sensible documentation.

**Comment by The-Compiler** [comment]
After thinking about this again, this is a bad idea UI-wise.
