### ISSUE TITLE
Unwanted creation of directories in `~`

### ISSUE THREAD

**Issue by NoctuaNivalis** [The-Compiler/qutebrowser#1977]
When starting `qutebrowser --backend=webengine`, the empty folders `~/.qutebrowser` and `~/.QtWebEngineProcess` are created. Both are empty, and removing them doesn't break anything. I'd prefer these directories not to be created. Note that my configuration is correctly read from `$XDG_CONFIG_HOME/qutebrowser`.

I'm not sure we can do anything about `~/.QtWebEngineProcess`, but surely `~/.qutebrowser` can be fixed.

**Comment by lahwaacz** [comment]
There is also https://github.com/The-Compiler/qutebrowser/pull/1637#issuecomment-242961120 for the same issue when running tests, but it's good to have an open issue for this - thanks!

I think that the redirection mentioned in https://github.com/The-Compiler/qutebrowser/pull/1637#issuecomment-246437648 is not applicable for normal instance of qutebrowser, so we'll probably have to wait until the Qt bug is fixed.

**Comment by The-Compiler** [comment]
Those are both Qt bugs, see [QTBUG-54258](https://bugreports.qt.io/browse/QTBUG-54258) and [QTBUG-55946](https://bugreports.qt.io/browse/QTBUG-55946).

Nothing I can do about them except maybe somehow set `$HOME` to some temporary directory during QtWebEngine initialization, which could have other unknown side-effects - so I'd rather not do that.

**Comment by genkimarshall** [comment]
Using qt5-webengine on Arch Linux, release 5.7.1-1, I don't experience this issue anymore. It seems QTBUG-54258 was closed when it was fixed, and now the fix is in the stable release. @The-Compiler, maybe it would be good to close your QTBUG-55946 bug as well? As it seems this isn't an issue anymore given that the directories aren't created in the first place. Unless I'm misunderstanding.
