### ISSUE TITLE
Can't install Arch Linux package or from AUR due to pyPEG

### ISSUE THREAD

**Issue by discursivemoth** [The-Compiler/qutebrowser#2058]
The Arch repos have python-pypeg2 2.15.1-3 but have been marked out of date (as of 10-24-2016) and fail pgp checks. Pip now installs pypeg 2.15.2 which qutebrowser doesn't recognize when trying to install.

**Comment by The-Compiler** [comment]
It's indeed out-of-date, but pypeg2 2.15.2 only fixes how examples are installed, so that's irrelevant.

As for the GPG error, my guess would be that you're running into https://bugs.archlinux.org/task/51447 - update your `archlinux-keyring` package and everything should be fine again - if not, feel free to reopen!
