### ISSUE TITLE
openhub.net reloading

### ISSUE THREAD

**Issue by nerdouille** [The-Compiler/qutebrowser#2061]
version info (using 0.8.2 release):
qutebrowser v0.8.2
CPython: 3.5.2+
Qt: 5.6.1
PyQt: 5.7

openhub.net seems to reload itself in an infinite loop, which makes it impossible to scroll down the page

**Comment by The-Compiler** [comment]
Huh, weird! This seems to be caused by the QtWebKit backend somehow...

FWIW you can interrupt the loading once with `<Ctrl-s>` and then it won't reload anymore - and in the future with `--backend webengine` things will work fine too. Unfortunately there isn't anything I can do to fix this with QtWebKit.
