### ISSUE TITLE
Please support privacy by reducing the fingerprint

### ISSUE THREAD

**Issue by JaneSmith** [The-Compiler/qutebrowser#2160]
I know that privacy isn't the main goal of qutebrowser, but many of us that browse the web do care about our privacy. I would like to see qutebrowser take measures to protect the privacy of its users by reducing its exposed fingerprint. Currently, Tor Browser is pretty much the only web browser out there that takes measures to reduce fingerprinting. I would love it if qutebrowser could join in the fight, while providing its unique keyboard-centric interface for efficient browsing.

You can test your web browser fingerprint by visiting: https://panopticlick.eff.org

The above test ranks qutebrowser as having a completely unique fingerprint, meaning that the user can be tracked just by all the identifying information that the browser is revealing, even if they're masking their IP address.

Here are some examples of things that could significantly reduce the fingerprint:

- Have an option to disable canvas support.
- Do not expose the list of available plugins to JavaScript.
- Do not expose the list of system fonts to JavaScript.
- Use a less revealing user agent string. Including version details and the qutebrowser name makes the user agent significantly more unique and trackable.
- Try to create a consistent environment, so that most qutebrowser users have a similar fingerprint to each other. It would be even better if you could imitate the fingerprint of other common browsers, such as the Tor Browser.

For more details on approaches to fighting fingerprinting, see sections 4.5. and 4.6. of the Tor Browser design document: https://www.torproject.org/projects/torbrowser/design/#identifier-linkability

**Comment by The-Compiler** [comment]
Apart from changing the user agent (which comes with other issues like breaking GitHub with the current QtWebKit backend, which is why I won't change it by default), Qt doesn't provide any API to do any of this.

It might be possible to do something via injected javascript, but that'd be something for after when there's a plugin API, which is tracked in #30 already.

**Comment by carbohydratesn** [comment]
It sucks that this issue was closed :(

This is the only problem I have with using qutebrowser every day - no privacy from invasive tracking.  I don't have to *see* any ads, but there's still a lot going on in the background...

> Qt doesn't provide any API to do any of this.

That's surprising, is there really no other way around this?  Could this change with the new backend?  Or will we have to wait until full plugin support?

**Comment by The-Compiler** [comment]
> This is the only problem I have with using qutebrowser every day - no privacy from invasive tracking. I don't have to see any ads, but there's still a lot going on in the background...

How do you prevent that with other browsers?

> That's surprising, is there really no other way around this? Could this change with the new backend? Or will we have to wait until full plugin support?

Why is it surprising? Those kinds of low-level things typically aren't exposed in general-purpose APIs, because it'd be a nightmare for Qt to maintain that.

With the new backend, we can at least run javascript independently from the website, so it *might* be possible to do some of those things - but then again, this is after #30 is implemented.

**Comment by lamarpavel** [comment]
So, we have Webkit/Blink as backend, then Qt as a wrapping API and then PyQt as a bridge ontop of that. Is there a way to bypass Qt and speak to the backend directly if we were willing to write some C? I have never looked at the Qt wrapper closely (or even from a distance), but the rendering backend is there somewhere and I'm wondering what would have to be done to reach it.

If that is actually infeasable, because you would breaking guarantees that Qt relies upon and thus cause crashes or so, how realistic is it that Qt would accept a patch or add a requested feature?

**Comment by The-Compiler** [comment]
I don't think we can do that.

I can't speak for Qt, but there's essentially two possibilities:

- It's something exposed via the Chromium content API (checking if CEF has something like that would be the first step) or via Chromiums internal settings (there's a file somewhere in the Chromium tree, but I don't remember where exactly), chances are a patch to Qt would be quite straightforward and I'd guess it'd be welcome.
- If it's something requiring Qt-specific patching inside Chromium/Blink/V8, chances get pretty low, especially if it's intrusive. Also, that patch *will* need to be rewritten for every new Qt version, because you can be pretty sure all the involved code will look different with every Chromium release. At that point, doing things from JS is the only way to maybe do something without going insane.

**Comment by lamarpavel** [comment]
Hm, I couldn't find any of the requested options as settings in `struct _cef_browser_settings_t` [1]. Regarding the user agent, there are several settings, eg [2], but we can already set that.
The API does not seem to have anything related to `canvas` or `fingerprint`, but that was just a quick search and I doubt that there is no setting at all to something as important as canvas drawing - it is probably part of some other settings with a different name.

I don't really have much time to dive into a new API as large as this one now, but anyone interested in these features might find the time to look through [3] more closely.

[1] http://magpcss.org/ceforum/apidocs/projects/(default)/_cef_browser_settings_t.html

[2] http://magpcss.org/ceforum/apidocs3/projects/(default)/_cef_settings_t.html#user_agent

[3] http://magpcss.org/ceforum/apidocs3/

**Comment by The-Compiler** [comment]
> I doubt that there is no setting at all to something as important as canvas drawing - it is probably part of some other settings with a different name.

It's quite possible. CEF (just like QtWebEngine) exposes what is part of the settings which are available via Chromium's content API.

If Chromium doesn't have such a setting (i.e. in its own Web UI), and it's not something Chromium needs to expose for plugins, Chromium probably won't have such a setting, as Google only cares about Google Chrome anyways.

That being said, it seems like there's a `--disable-reading-from-canvas` commandline switch for Chromium. It's entirely possible we can expose that at least as an option only set after a browser restart. That also means there is maybe such an option somewhere which could be exposed as a QWebEngineSetting in Qt.

**Comment by The-Compiler** [comment]
FWIW I split off the Canvas fingerprinting thing to #2235, so I suggest you subscribe to that if interested :wink:
