### ISSUE TITLE
Following links to Youtube channels in the same tab don't get added to the history

### ISSUE THREAD

**Issue by sfgasdfsafggfgg** [The-Compiler/qutebrowser#2161]
Running version `v0.8.4`, `Git commit: v0.8.0-1914-gaf766ad (2016-12-02 09:43:05 +0100)` using the QtWebengine backend.

Entering a url to go to using `:open` adds it to the history, and so does opening a link in a new tab (Youtube channels also get added to the history when opened this way).

Following links to Youtube channels in the same tab from other Youtube channels however doesn't add them to the history. This suggests some types of link on other websites won't get added to the history if followed in the same tab.

To reproduce:
1. Go to a Youtube channel you've never visited before that won't be in your history, e.g. `:open https://www.youtube.com/user/h3h3Productions/channels`
2. Follow a link in the same tab to a different Youtube channel
3. Type `:open `, type part of the name of the Youtube channel you just visited and press Tab
4. The new channel doesn't appear in the history completions.

**Comment by haasn** [comment]
I had a similar bug with pentadactyl's yank feature, because as it turns out, YouTube doesn't use normal links. For “performance reasons” or whatever braindead web dev nonsense, they actually use AJAX requests and rewrite the DOM in JavaScript instead.

And ironically, they don't even do it properly, because they forget to update some of the <head> properties, like the shortlink, which is why :yank broke.

Solution: Never click on inter-youtube links, just open them in new tabs. That forces the normal, sane behavior.

**Comment by haasn** [comment]
I looekd into it, apparently HTML5 has a History API that lets you change the “displayed URL” of the current page without actually leaving the page.

Sounds like webkit doesn't implement the History API properly (i.e., add it to the history)

**Comment by sfgasdfsafggfgg** [comment]
@haasn I have this issue with the webengine backend

**Comment by The-Compiler** [comment]
Thanks for looking into this, @haasn!

QtWebEngine doesn't really have a history API, see [QTBUG-51668](https://bugreports.qt.io/browse/QTBUG-51668) for that. What Qt does currently is storing the history item when a page finished loading. I guess there's no way to detect fake pageloads like this correctly currently, so I'm closing this.
