### ISSUE TITLE
Privacy enhancing features

### ISSUE THREAD

**Issue by vbrandl** [The-Compiler/qutebrowser#2199]
Hi
I think some privacy enhancing features in the browser would be really nice:

 - something like [HTTPS Everywhere](https://www.eff.org/https-everywhere) or [Smart HTTPS](http://mybrowseraddon.com/smart-https.html)
 - finetuning of TLS like selecting the supported ciphers, TLS/SSL versions or OCSP behaviour
 - in general some visual indikator about the encryption status (maybe like red -> plain HTTP, yellow -> weak cipher, green -> good encryption)
 - some per domain rightsmanagement like uMatrix or NoScript for scripts, cookies, plugins, frames, ...
 - caching of often used scripts, delivered through CDNs like [Decentraleyes](https://github.com/Synzvato/decentraleyes/) does

I think this would be some great features to protect the users privacy.
Anyway great work. I love this browser. Probably the best one I ever used ;)

**Comment by sfgasdfsafggfgg** [comment]
[Plugin API](https://github.com/The-Compiler/qutebrowser/issues/30) and [per domain settings](https://github.com/The-Compiler/qutebrowser/issues/27) are planned.

**Comment by The-Compiler** [comment]
Going through those one by one:

 > - something like [HTTPS Everywhere](https://www.eff.org/https-everywhere) or [Smart HTTPS](http://mybrowseraddon.com/smart-https.html)

Tracked in #335 

>  - finetuning of TLS like selecting the supported ciphers, TLS/SSL versions or OCSP behaviour

Not possible using the API we get from QtWebEngine currently - and unless it's possible via the Chromium content API somehow, I doubt that'll change.

>  - in general some visual indikator about the encryption status (maybe like red -> plain HTTP, yellow -> weak cipher, green -> good encryption)

The URL is already yellow if there were any SSL errors, other than that there isn't really much I can do either. It being red for plain HTTP might be worth some more thoughts, but since it's currently red for loading errors, that might be confusing.

>  - some per domain rightsmanagement like uMatrix or NoScript for scripts, cookies, plugins, frames, ...

#27 like @pkill-nine mentioned :wink:

 > - caching of often used scripts, delivered through CDNs like [Decentraleyes](https://github.com/Synzvato/decentraleyes/) does

Mentioned as a plugin idea in #30 already.


Since this all seems to be handled by other issues, I'm closing this.
