### ISSUE TITLE
[Feature]: Gopher support

### ISSUE THREAD

**Issue by prologic** [The-Compiler/qutebrowser#321]
(I didn't even know this browser existed! -- WoW)

Since I'm a really big fan of [Gopher](http://gopherproject.org) recently it would be really nice if Gopher support was added to qutebrowser. I would in all likelihood probably start using qutebrowser as my primary GOpher client and/or primary Web/Gopher Browser.

**Comment by The-Compiler** [comment]
[Dooble](https://github.com/textbrowser/dooble) seems to be a Qt based browser with some partial Gopher support.

Just thought I'd leave this here, but don't expect me to work on Gopher support in the near future :wink:

**Comment by The-Compiler** [comment]
So... I'm not very interested in this personally, and unfortunately there's always a lot of things to do. I unfortunately don't see this happening, and don't think it should be in qutebrowser's core.

However, I added a line about custom URL schemes to the plugin API ideas (#30), so maybe at some future point it'd be possible for someone to write a plugin for this.

**Comment by bzbug** [comment]
I understand this is not top priority for now, but I just wanted to add that support for other protocols like Gopher and Gemini _should_ be considered more important than it probably looks. It's one thing to fine-tune the Web browsing and implement new nice features when the support for the Web is already there and it's another to add support for other important procotols (which are also _better_ than Bloated Wide Web, btw). The removal of Gopher protocol in the first place from most browsers is just an historical accident, not a good thing that came to be because Web is technically superior or something, and the primary goal of a browser is still to show the user the information he requested. As much as I need all those top priority nice features like Tree Tabs and uMatrix and the Plugin API and fix for the memory leak(s) and support for Adblock CSS rules etc., I'd prefer first to be able to at least _get_ the information that I'm looking for, and then organize it with Tree Tabs, manage my Request Policy and so on.

**Comment by The-Compiler** [comment]
> I understand this is not top priority for now, but I just wanted to add that support for other protocols like Gopher and Gemini _should_ be considered more important than it probably looks.

I still believe this is not something the majority of qutebrowser users will care about, and while extensions should make it possible to provide custom protocols, I still don't see why this should be in the core. I'm also still unlikely to actually write such an extension myself.

> The removal of Gopher protocol in the first place from most browsers is just an historical accident

I doubt it. There were and are good reasons for such a removal (notably, it being an ancient protocol with no widespread usage: *In February 2022 Veronica indexed 325 gopher servers*).

> I'd prefer first to be able to at least _get_ the information that I'm looking for

What information is there that you can't get via HTTP or a HTTP gateway to Gopher/Gemini?

**Comment by bzbug** [comment]
> There were and are good reasons for such a removal (notably, it being an ancient protocol with no widespread usage: In February 2022 Veronica indexed 325 gopher servers).

Well, that's the thing. I was talking about its early removal before it became this obscure procotol no one heard about. The removal of the protocol has lead to it being so unpopular, not the other way around. I'm betting if more people knew about it, there'd be a lot more users out there who'd like it better than the Web. It is an historical accident in the sense of Web being _worse_ because its very degisn allows presentation hinder the content (which always inevitably leads to tons of garbage content in a world where marketing simply _exists as a concept_), but yet Web has won and is now known world-wide. What I meant to say is that the popularity of the Web does not mean the Web is a better technology and other protocols like Gopher or Gemini don't matter enough to implement them in a browser. Popularity is not a sign of quality, and Web's popularity is an accident when we think about its quality.

> What information is there that you can't get via HTTP or a HTTP gateway to Gopher/Gemini?

... for starters, Floodgap's gateway blocks me, and since I wasn't using Tor or VPN or proxy for the connection, and also tried different User Agents (even one of Mozilla's recent), I'm guessing they use fingerprint to determine somehow that I'm using a less popular browser which is suspicious to them. I will mail them when I'm able to try and solve this.

But the main reason actually is that I simply don't see why using an HTTP gateway to access Gopher/Gemini space is considered a solution here when we talk about a browser. What I meant to say is that, since we're talking here about a browser and what problems it solves for the user, it'd only make sense to make _the browser_ solve the problem of retrieving Gopher/Gemini resources, as it was intended. I mean, I could install Chrome and probably browse the Gopherspace from it using Floodgap's gateway right now, but I'd be leaving QB for that, and I could figure out and finally solve the issue of the Floodgap's blocking and browse the Gopherspace from QB using their gateway, but I'd be relying on the gateway to use a protocol that is already supported by other browsers. So, let me fix what I said:

> I'd prefer first to be able to at least _get_ the information that I'm looking for *_directly from the browser_, since it's a discussion about how to make that browser better rather than about how a particular user could temporarily access some info using other means.

I could use `w3m` for Gopher, too. Does it mean everyone should be doing that forever instead of using QB for browsing the Gopher space? Same goes for gateways. When you replace 'Gopher' with 'Web', you can hear how ridiculous it sounds: "We don't consider supporting HTTP top priority yet, the more important thing right now is Plugin API which you can use for more convenient browsing of your HTML-pages _after you go and retrieve those by foot or wait for a delivery by pidgeons_".

---

I'm not trying to force you to implement this in the core or something, my original message was exactly what I said it was - pointing out that Gopher and Gemini are important, should not be forgotten, and there are more people who want this feature than it seems. In case someone'll think about implementing it later, find this issue and reconsider because there's only one person requesting it and not much action.
