### ISSUE TITLE
Open files from downloads

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#39]
The user should be able to open files directly from qutebrowser (rather than downloading).

The associations should be made via `QDesktopServices` or overridden per mimetype.

**Comment by The-Compiler** [comment]
The implementation for this would look something like this:

* Add a new mode, say `download` to `PromptMode` in `utils/usertypes.py`
* Handle that mode correctly in `mainwindow/statusbar/prompter.py`
   * Add it to `KEY_MODES` with `usertypes.KeyMode.prompt` - this means the keybindings of the `[prompt]` section will be used.
   * Change `_display_question` and `prompt_accept` to handle `PromptMode.download` like `PromptMode.text`.
   * Add `OPEN_DOWNLOAD = object()` somewhere at the top so we have a magic return value for "the user wanted to open a download".
   * Add a new command `:prompt-open-download` by writing a function with a `@cmdutils.register` decorator - it'll probably look similar to `prompt_yes`, only that it checks for the `download` mode and sets the answer to `OPEN_DOWNLOAD`.
* Handle this return value in `browswer/downloads.py`
   * Set the mode to `PromptMode.download` in `_prepare_question`
   * to be continued...

**Comment by The-Compiler** [comment]
What would also be nice is to force rendering something in the browser (say, a html with `Content-Disposition: attachment`), but we'd need to find out the mimetype somehow, and I'm not sure if that's possible with QtWebEngine.

**Comment by Kingdread** [comment]
There's also the question when to clean up files, e.g. Firefox downloads them to `/tmp/mozilla_*/` and leaves them there until Firefox is closed. This may lead to problems if the started application outlasts Firefox, since the file will be gone.

So should we do the same and document this as the correct behaviour? Or do we monitor the started process (if that's possible with the `QDesktopServices::openFile`) and only delete it if the process is dead? Or do we rely on manual cleanup (e.g. a command for cleaning temporary download files)?

**Comment by lahwaacz** [comment]
At least on Linux, you can use something like `lsof` to find out if the file is still used or not.

**Comment by The-Compiler** [comment]
I'd expect the file being deleted when the browser is closed to be honest. If people complain we can always add an option to keep them around.

Not actually quitting qutebrowser and monitoring the process/file seems like a lot of unnecessary trouble :wink:
