### ISSUE TITLE
cookies in netscape format

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#50]
For some actions I'd be useful to have cookies in the standard netscape format:
- External download handler (e.g. `wget`)
- Userscripts

We don't really want to save them that way, but we should be able to export and maybe import it.

References:

http://www.cookiecentral.com/faq/#3.5
https://docs.python.org/3.4/library/http.cookies.html
http://qt-project.org/doc/qt-4.8/qnetworkcookie.html

Notes:
- Second column (flag): `TRUE` if domain starts with `.`, else `FALSE`
- if a cookie is a http-only cookie domain is prepended with a `#HttpOnly_`
- Python's `http.cookiejar.MozillaCookieJar` might help

**Comment by The-Compiler** [comment]
not going to happen with QtWebEngine current's cookie API.

**Comment by noxultranonerit** [comment]
Nothing to do with the API, since the cookies are stored in a sqlite3 database format, the conversion to netscape format can be done using a shell script which is really simple, take a look at this 
https://github.com/noxultranonerit/SimpleScripts/blob/master/QtWebengineNetscapeCookie
Hope it helps.
