### ISSUE TITLE
Issues with URL with quotes/spaces

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#509]
`QUrl` behaves weird when going to [this page](http://wiki.cyanogenmod.org/w/Devices#vendor=) and selecting a vendor with spaces (e.g. *Barnes & Noble*). No matter how we're requesting the URL (even with `QUrl::FullyDecoded`), either `%22` or `%20` show up in the link, which breaks `go` or `yy`.

**Comment by Carpetsmoker** [comment]
Firefox shows this in the URL bar:
	
	http://wiki.cyanogenmod.org/w/Devices#vendor="","Barnes & Noble";

And copies it as:

	http://wiki.cyanogenmod.org/w/Devices#vendor=%22%22,%22Barnes%20&%20Noble%22;

Which is the same as qutebrowser what qutebrowser copies with `yy`:

	http://wiki.cyanogenmod.org/w/Devices#vendor=%22%22,%22Barnes%20&%20Noble%22;

The page incidentally has a useful `console.log`, which in Firefox says:

	"hashchange" "vendor="","Barnes & Noble";"

But in qutebrowser it says:

	hashchange vendor=%22%22,%22Barnes%20&%20Noble%22;

Pasting the above URL works in Firefox; but not in qutebrowser, otter-browser,
dwb, midori, and chromium. It does seem to work in Firefox & Internet Explorer.

The problem is, I think, the space in the hash, which AFAIK is not allowed.
WebKit doesn't seem to like it... Not sure if this is actually a bug, or a
choice of the WebKit people to do it this way...

**Comment by The-Compiler** [comment]
As you said it might be the page doing non-standard stuff, so I'm closing this.
