### ISSUE TITLE
hangout session does not start

### ISSUE THREAD

**Issue by rif** [The-Compiler/qutebrowser#527]
This browser it's getting better and better and I started to use it as my primary browser. Thank you!

I have this issue with the google-talkplugin seems not to be enabled.

When I start a hangout session I get the following message in the upper left part:
Select 'Allow' for both Google Talk plugins in order to access the video call. See detailed instructions

I used :set content allow-plugins true but still no show. Any suggestions?

**Comment by The-Compiler** [comment]
I've taken a quick look at how that plugin works - the Archlinux package installs NPAPI files to `/usr/lib/{firefox,iceape,iceweasel,midbrowser,mozilla,xulrunner,xulrunner-addons}/libnp{googletalk,o1d}.so`.

QtWebKit should load NPAPI plugins from `/usr/lib/{firefox,mozilla}/plugins` so that *should* work fine.

I wonder if the plugin just asks the browser for permission to use camera/microphone and QtWebKit doesn't implement that. Can you maybe share the link for "detailed instructions" so I can take a look at how it typically looks in other browsers?

**Comment by rif** [comment]
Here is  the link: https://support.google.com/hangouts/?p=plugin

**Comment by The-Compiler** [comment]
I can reproduce this, and seems like it's some kind of QtWebKit issue.

Here's how it looks for me in qutebrowser:

![hangouts_qutebrowser](https://cloud.githubusercontent.com/assets/625793/6674942/8a21a944-cc1d-11e4-8df9-f13909cc4e31.png)

In [Otter Browser](https://github.com/OtterBrowser/otter-browser), I get the text you mentioned and an icon to load plugins (`Action::LoadPluginsAction` in the code), but nothing happens when clicking it:

![hangouts-otter-1](https://cloud.githubusercontent.com/assets/625793/6674972/b6ba51d6-cc1d-11e4-8ea5-8e42c1e4fba4.png)
![hangouts-otter-2](https://cloud.githubusercontent.com/assets/625793/6674980/cc276752-cc1d-11e4-918b-b1fa10f0cfc7.png)

I'll report this upstream in a few days.

**Comment by The-Compiler** [comment]
In the meantime I get "We're sorry but this product does not support your browser at this time." when not faking the user-agent, and the same thing as above when faking it.

I'm going to guess this is just not implemented in QtWebKit, and will hopefully work with #666 (QtWebEngine/Chromium backend). Sorry!
