### ISSUE TITLE
Unable to remove predefined searchengines

### ISSUE THREAD

**Issue by oed** [The-Compiler/qutebrowser#533]
The searchengines that are defined by default are always readded after a manual edit of the `qutebrowser.conf` file. They are added right after the browser is started.
There is also no way to remove searchengines using the gui.

Another problem, that isn't really related, is that after adding a new searchengine it wont appear in the list until qute is restarted.

**Comment by The-Compiler** [comment]
That is currently the expected behaviour (just like missing/new settings being readded) - but I agree it's confusing. It's definitely something I should look at with the config format rewrite (#499). For the search engines, never adding new defaults makes sense, but for other stuff maybe less - see also #525 for the same thing with keybindings. Right now, you have to set a search engine to an empty value to "remove" it.

The config is saved periodically all 15s (`general -> auto-save-interval`) so I think that's why you saw the second behaviour - for me it appears in the config without closing qutebrowser after a few seconds.

**Comment by oed** [comment]
Yeah, I thought that was the case. It's not really a big issue but a little anoying.

**Comment by error800** [comment]
This annoyed me enough to remove it ;)
https://github.com/The-Compiler/qutebrowser/pull/542
