### ISSUE TITLE
Option for manual completing using tab

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#557]
The `completion -> show` option should be enhanced to actually not burn CPU cycles for the completion, and to show the completion when the user presses tab.

/cc @flavi0 @toofar

**Comment by toofar** [comment]
Just to make a note that I tested this for history completion (with a large history) while there isn't a delay between typing each letter anymore there is still a (for ~35000 entries on a fast PC) a delay of about 0.5s and more than that for the first completion when the model is loaded. So that is still a pretty noticeable delay after pressing tab so don't expect magic.

**Comment by The-Compiler** [comment]
Yeah, I think a small delay after pressing tab isn't an issue - but having a completion and some lag when just trying to type an URL by hand might be.

So do you already happen to have a patch for this? :wink:

**Comment by toofar** [comment]
Oh not a good one. I just changed `completion/completionwidget.py:completion_item_next()` to enable completion and call `schedule_completion_update()`. But that breaks the down keybinding and wasn't very consistent.

**Comment by The-Compiler** [comment]
See #705.
