### ISSUE TITLE
[Security] please remove weak ciphers and restrict mixed content handling

### ISSUE THREAD

**Issue by revuwa** [The-Compiler/qutebrowser#594]
I've tried to make a (quick and dirty) comparison of 
* Chromium v43.0.2342.0
* Firefox v36.0.4 and
* qutebrowser v0.1.4

to illustrate what I mean:

{graphic replaced with post: https://github.com/The-Compiler/qutebrowser/issues/594#issuecomment-88980089}

IMHO Firefox seems to be a legitimate 'template' for that.
Thanks in advance for any hint or support in that case.

Finally, I would like to thank you all for your enthusiasm and this great browser-project!

Sources:
Chromium logo: https://www.chromium.org/
Firefox logo: https://www.mozilla.org/en-US/firefox/new/
qutebrowser logo: https://github.com/The-Compiler/qutebrowser
FREAK vulnerability check: https://freakattack.com/
all other test results: https://www.ssllabs.com/ssltest/viewMyClient.html

**Comment by The-Compiler** [comment]
Thanks for the detailed report! What would be interesting to know is the distribution you're on, as well as the OpenSSL and Qt versions reported in `:open qute:version`.

Let's look at those problems one by one:

## FREAK

This was apparently fixed in OpenSSL 1.0.2a, 1.0.1m, 1.0.0r and 0.9.8zf. On the Ubuntu Trusty VM I'm testing this on, they're apparently still shipping OpenSSL 1.0.1f, on my Archlinux machine with OpenSSL 1.0.2 I'm unaffected.

It seems Ubuntu [patched OpenSSL](http://www.ubuntu.com/usn/usn-2459-1/) accordingly, but I wonder why I still see it listed as vulnerable then... I haven't tested if it looks better on Debian Jessie - but it might sense to report bugs against Ubuntu and perhaps Debian about this, as it seems to affect QtWebKit there in general - do you want to do that?

But yeah. Another example how it's a [bad idea](https://blog.hboeck.de/archives/864-What-the-GHOST-tells-us-about-free-software-vulnerability-management.html) to try to stick to old versions and maybe find out about and patch bugs from upstream...

## RC4 SSL ciphers

I'm discussing disabling RC4 ciphers in general with the Qt project - unfortunately there are still pages like https://aa.com/ which use RC4, so it seems disabling it by default is not really possible right now... :disappointed: 

I wonder how Firefox manages to not list RC4 in the test, but still is able to connect to https://aa.com/ though...

Either way, the used ciphers should be configurable so users can optionally disable RC4 at the cost of breaking some pages. See #192 for that (which I accidentally closed it seems).

## Mixed content handling

I don't really get what's happening here - I sometimes see "Yes", sometimes "No". Though my connection is rather flaky right now - I'll take a closer look at that later.

Related code: [StackOverflow](http://stackoverflow.com/questions/20613894/how-to-use-qtwebkit-and-block-mixed-content), [WebKit](https://bugs.webkit.org/show_bug.cgi?id=29003), [QtWebKit](http://code.qt.io/cgit/qt/qtwebkit.git/tree/Source/WebCore/loader/MixedContentChecker.cpp)

**Comment by revuwa** [comment]
> What would be interesting to know is the distribution you're on, as well as the OpenSSL and Qt versions reported in :open qute:version.

Sorry for my slackness; here we go:
# [VM] Windows 8.1 64bit (v6.2.9200, fully patched) 
* Midori v0.5.9 | about:version

GTK+ 3.10.4 (3.10.4)	Glib 2.40.0 (2.40.0)
WebKitGTK+ 2.2.6 (2.2.6)	libSoup 2.44.2
cairo 1.12.16 (1.12.16)	libnotify No
gcr No	granite No
* Chromium v43.0.2353.0 (64-bit) | about:version

Blink: 537.36 (@192890)
JavaScript: V8 4.3.62
Flash: (Disabled)
* Firefox v37.0 | about:about

NSPR: 4.10.8
NSS / NSSSMIME / NSSSSL: 3.17.4 Basic ECC
NSSUTIL: 3.17.4
* qutebrowser v0.1.4 | :open qute:version

CPython: 3.4.2
Qt: 5.4.1, runtime: 5.4.1
PyQt: 5.4.1
colorlog: no
colorama: no
pypeg2: 2.15
jinja2: 2.7.3
pygments: 2.0.1
Webkit: 538.1
Harfbuzz: system
SSL: OpenSSL 1.0.1i 6 Aug 2014

![windows](https://cloud.githubusercontent.com/assets/7300276/6968980/65e19188-d96b-11e4-8712-0a3fcf65bd3e.png)

# Linux Mint 17 "Qiana" 64bit (Linux-3.16.0-28-generic-x86_64, fully patched)
* Midori v0.4.3 | about:version

WebKitGTK+	1.10.1 (2.4.8)
GTK+	2.24.13 (2.24.23)
Glib	2.34.2 (2.40.2)
libsoup	2.40.2
cairo	1.12.8 (1.13.1)
libnotify	0.7.5
libunique	1.1.6
libhildon	No
Platform	X11; Linux x86_64
* Chromium v41.0.2272.76 (64-bit) | about:version

Blink	537.36 (@191030)
JavaScript	V8 4.1.0.21
Flash	(Disabled)
* Firefox v37.0 | about:about

NSPR: 4.10.8
NSS / NSSSMIME / NSSSSL: 3.17.4 Basic ECC
NSSUTIL: 3.17.4
* qutebrowser v0.1.4 | :open qute:version

CPython: 3.4.0
Qt: 5.2.1, runtime: 5.2.1
PyQt: 5.2.1
SIP: 4.15.5
colorlog: no
colorama: 0.2.5
pypeg2: 2.15
jinja2: 2.7.3
pygments: 2.0.2
Webkit: 537.21
Harfbuzz: old
SSL: OpenSSL 1.0.1f 6 Jan 2014

![linux](https://cloud.githubusercontent.com/assets/7300276/6969063/0207efc6-d96c-11e4-873a-88e25bf23cd2.png)

# FREAK
> [...] it might sense to report bugs against Ubuntu and perhaps Debian about this, as it seems to affect QtWebKit there in general - do you want to do that?

I'll try to figure out what's exactly the matter here and try to report that the right way to that OS-projects.

# RC4 SSL ciphers
> I wonder how Firefox manages to not list RC4 in the test, but still is able to connect to https://aa.com/ though...

I think this changed with Firefox v36.0: "No longer accept insecure RC4 ciphers whenever possible".
Source: https://www.mozilla.org/en-US/firefox/36.0/releasenotes/

So it seems, that you connect >more< or less insecure to that kind of sites:
![ffcert](https://cloud.githubusercontent.com/assets/7300276/6968808/d84667aa-d969-11e4-853a-7b085987191b.PNG)

Once the GitHub user @pejakm sayd the following: "It's better to have no encryption at all than to have possibly compromised encryption. Using the latter provides false sense of security.", and I think he/she/it is right.

> Either way, the used ciphers should be configurable so users can optionally disable RC4 at the cost of breaking some pages. See #192 for that (which I accidentally closed it seems).

That would be so great; I totally appreciate this idea.

# Mixed content handling
> I don't really get what's happening here - I sometimes see "Yes", sometimes "No". Though my connection is rather flaky right now - I'll take a closer look at that later.

Here's the link, why it seems to be a security risk in general: https://community.qualys.com/blogs/securitylabs/2014/03/19/https-mixed-content-still-the-easiest-way-to-break-ssl

**Comment by The-Compiler** [comment]
Thanks again for your detailed and elaborate reports - if only all bug reports were like this! :+1:

## POODLE

Even though you haven't mentioned this, I'll quickly talk about it as well - I've looked into disabling SSLv3 in #192 and it doesn't seem to be easily possible. So there again it'd be the distributions job to backport the necessary fixes...

## FREAK

Hm. It's weird to see qutebrowser with Qt 5.4.1 on Windows is affected as well. It seems to use OpenSSL there as well, probably shipped with either PyQt or Qt. I suggest waiting for Qt 5.5 (scheduled for May) - and if nothing changes there, reporting this to Qt (or PyQt) as well. 

For both POODLE and FREAK, unfortunately I don't think there's anything I can do from my side to prevent those issues with older Qt/OpenSSL versions :disappointed: 

Can you maybe test with some pure-Qt browser as well, such as [Otter Browser](http://otter-browser.org/)?

## RC4

> Once the GitHub user @pejakm sayd the following: "It's better to have no encryption at all than to have possibly compromised encryption. Using the latter provides false sense of security.", and I think he/she/it is right.

I happen to disagree :wink:. *Any* encryption is better than no encryption - and if it's just to defend against simple sniffing attacks in public WiFis for example.

A much better approach would probably be to detect the usage of an RC4-cipher and then mark the URL in the "warning" color (orange) instead of green, like it's done when ignoring SSL errors currently. I took a quick look and it turned out harder to implement than I hoped it'd be (note to self: see [NetworkManager::setSSLConfiguration](https://github.com/QupZilla/qupzilla/blob/v1.8/src/lib/network/networkmanager.cpp#L138-L157)). I'll look at that after releasing v0.2 though.

## Mixed content handling

I can now reproduce these results with a stable connection, and I see the same in other QtWebKit browsers. From what it looks, it's a missing "feature" in QtWebKit - I don't know if I'll be able to add this on top of QtWebKit.

**Comment by revuwa** [comment]
Sorry for the looong intermission.

I've tested the current version of qutebrowser now under an Ubuntu box with the following details:
qutebrowser v0.3.0
CPython: 3.4.3
Qt: 5.4.1, runtime: 5.4.1
PyQt: 5.4.1
Style: QGtkStyle
Desktop: Lubuntu
sip: 4.16.6
colorlog: no
colorama: no
pypeg2: 2.15
jinja2: 2.7.3
pygments: 2.0.2
yaml: 3.11
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.1f 6 Jan 2014
Frozen: False
Platform: Linux-3.19.0-22-generic-x86_64-with-Ubuntu-15.04-vivid, 64bit
OS Version: Ubuntu, 15.04, vivid

The result is, that qutebrowser is not vulnerable to:
- Logjam, FREAK and POODLE (min. used protocol is: TLS 1.0)

any longer (on a patched Linux box).

I also played around a little bit with Otter Browser, like you mentioned. The 'SSL Client Test'-site from Qualys SSL Labs (https://www.ssllabs.com/ssltest/viewMyClient.html) looks very identical to the one of the current qutebrowser. The only slightly difference I've found is, that Otter is shipped with exactly 20 supported 'Cipher Suites' less. But the last 6 ciphers, marked as 'WEAK' and the final one called 'TLS_EMPTY [...]' are exactly the same on both browsers, and should be removed, because (among other things, a 52 hours RC4 cipher crack POC):
https://www.youtube.com/watch?v=d8MtmKrXlKQ

Otter seems to provide a do-it-yourself option for that. Under Tools -> Preferences (CTRL+F12) -> Advanced -> Security, you can add-, remove- and modify the preference order of the used cipher suites.
If there would be something similar, for example text file based for qutebrowser, this definitely would do the trick for everyone, in my eyes. What do you think?

**Comment by revuwa** [comment]
PS: a very cool site to check your browser's cipher suites and get further detailed informations about, is: https://www.howsmyssl.com/ if you want to give it a try.
[the SSL-client of qutebrowser v0.3.0 is "bad", because of "insecure cipher suites"].

**Comment by The-Compiler** [comment]
Now that [Qt disabled RC4](https://codereview.qt-project.org/#/c/148906/) too I added some code to do the same with earlier Qt versions.

Things hopefully look a bit better now, let me know if you still find something though.

As for the mixed-content handling issues (which I couldn't reproduce now), that (and SSL handling in general) should hopefully get a lot better with the upcoming support for the QtWebEngine backend (which is based on Chromium).

**Comment by D-Nice** [comment]
qt.args should allow one to resolve this. Having issues disabling ciphers, but at least one can disable both active and passive mixed content by adding: `enable-strict-mixed-content-checking` to QtWebEngine via qt.args.
