### ISSUE TITLE
Add option to disable third-party cookies.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#607]
The `content -> cookies-accept` setting should get a new value (`no-3rdparty` or so?) to not accept 3rd-party cookies.

* [Test page](https://dl.dropboxusercontent.com/u/105727/web/3rd/third-party-cookies.html)
* [More informations](http://en.wikipedia.org/wiki/HTTP_cookie#Third-party_cookie)
* [RFC 6265](https://tools.ietf.org/html/rfc6265#section-7.1)
* [Related commit in Otter](https://github.com/OtterBrowser/otter-browser/commit/eaed7a67d70686a31cc9497b86d1e09aaa423bac)

**Comment by moozzz** [comment]
Hi The-Compiler! As a former luakit user I found the way luakit blocked cookies quite convenient. Instead of blocking 3rd-party cookies, luakit offered simple domain-based cookie blocking via cookie.blacklist and cookie.whitelist which were placed in ~/.config/luakit. This part of the code consisted only of 73 lines so it seems to be easier to implement (at least on this stage of development).

The luakit's config file had to be then extended like this:

require "cookies"   # simple cookie manager
requrie "cookie_blocking"   # the abovementioned, short code
cookies.default_allow = false   # to block all cookies by default and hence disable cookie.blacklist

I don't know how time-consuming it would be to convert a Lua code into Python though... Anyway, if you like this suggestion, I could try to implement it.

**Comment by The-Compiler** [comment]
This (and much more) will become possible when domain-wide settings (#27) are implemented.
So at the moment I think it's a bad idea to do a very specialized implementation (even if it would probably be easy), and then have two ways of doing the same thing.

That being said, 3rd party cookie filtering also should be an easy thing to implement - so if you feel like working on that, please let me know and I'll help where I can!

**Comment by The-Compiler** [comment]
@moozzz since you started working on this, can you open a work-in-progress pull request so nothing gets lost and I can take a first look at the code? If you're still struggling with getting the original URL for a page, I'm happy to help :smile:

**Comment by Carpetsmoker** [comment]
You can use `QWebSettings::ThirdPartyCookiePolicy` to disable 3rd party cookies. See: http://doc.qt.io/qt-5/qwebsettings.html#ThirdPartyCookiePolicy-enum

Did you work on this @moozzz ? I saw you forked the repo on the 24th (same date as comment), but no commits? Otherwise I'll do it since this is a feature I would very much like before I actually start using QuteBrowser :-)

**Comment by The-Compiler** [comment]
As discussed in IRC, according to @Emdek of Otter Browser, using `QWebSettings::ThirdPartyCookiePolicy` doesn't work (probably because we're using a custom `QNetworkCookieJar` subclass?).

He ended up using [some custom code](https://github.com/OtterBrowser/otter-browser/commit/eaed7a67d70686a31cc9497b86d1e09aaa423bac), and I think something similiar to that is what @moozzz was working on, but I haven't seen the code yet :wink:

**Comment by Carpetsmoker** [comment]
@The-Compiler  I added this line in `init()` in `config/websettings.py` as a test:

    QWebSettings.globalSettings().setThirdPartyCookiePolicy(QWebSettings.AlwaysBlockThirdPartyCookies)

And this seems to work. Starting with `--temp_basedir` *without* this line and visiting arstechnica gives me:

	[/tmp/qutebrowser-basedir-q7dhe0av]% grep -Eo 'domain=[^ ]*' data/cookies | cut -d= -f2 | sort -u
	.254a.com;
	.adnxs.com;
	.adsby.bidtheatre.com;
	.adsrvr.org;
	.advertising.com;
	.arstechnica.com;
	.bidswitch.net;
	.c.appier.net;
	.condenast.demdex.net;
	.connexity.net;
	.demdex.net;
	.doubleclick.net;
	.m6r.eu;
	.mathtag.com;
	.netseer.com;
	.parsely.com;
	.pixel.rubiconproject.com;
	.revenuemantra.com;
	.revsci.net;
	.rfihub.com;
	.rubiconproject.com;
	.scorecardresearch.com;
	.simpli.fi;
	.tidaltv.com;
	.turn.com;
	.w55c.net;
	arstechnica.com;
	cdn.turn.com;
	match.rundsp.com;
	tap.rubiconproject.com;
	tap2-cdn.rubiconproject.com;


and without:

	[/tmp/qutebrowser-basedir-dy1esjbm]% grep -Eo 'domain=[^ ]*' data/cookies | cut -d= -f2 | sort -u
	.arstechnica.com;
	arstechnica.com;

**Comment by Carpetsmoker** [comment]
We probably *do* need some custom code once we want to allow cookie settigns on a per-domain basis, but right now this seems like a good temporary solution?

**Comment by The-Compiler** [comment]
Oh, that's unexpected (and nice!). I'll add that to the `cookies-accept` setting after I'm done with some other things I'm working on, unless you submitted a PR until then already :wink:

**Comment by moozzz** [comment]
Hi guys! Sorry for my late reply...

@The-Compiler, yes I'm still working on this problem and yes I'm still struggling with getting URL of the current page =D. But since I'm not a programmer and my knowledge of OOP is far from being even 1/10 of yours, my progress goes much more slowly than yours =D

But here is a couple of things I managed to implement in qutebrowser (based on Otto):

First of all, we need to construct a cookie URL from a cookie entry in the CookieJar. For this I used the function:
```python
def cookie_url(self, a_cookie):
    """Convert a cookie to url."""
    url = QUrl()
    if a_cookie.isSecure():
        url.setScheme("https")
    else:
       url.setScheme("http")

    a_cookie_domain = a_cookie.domain()
    if a_cookie_domain.startswith('.'):
        url.setHost(a_cookie_domain[1:])
    else:
        url.setHost(a_cookie_domain)

    url.setPath(a_cookie.path())
    return url
```

Then we need a function that would compare the domains of two URLs and return True if they are equal and False if not. My implementation:
```python
def is_domain_the_same(self, url1, url2):
    """Compare two urls."""
    url1_Tld = url1.topLevelDomain()
    url2_Tld = url2.topLevelDomain()

    if url1_Tld != url2_Tld:
        return False

    url1_Domain = '.' + url1.host().lower()
    url1_Domain = url1_Domain[:-len(url1_Tld)]

    url2_Domain = '.' + url2.host().lower()
    url2_Domain = url2_Domain[:-len(url2_Tld)]

    if url1_Domain[1:] == url2_Domain[1:]:
        return True

    return False
```

Finally, a function is required that would purge third party cookies (similar to purge_old_cookies() ):

```python
def purge_third_party_cookies(self, current_url):
    """Purge third party cookies."""
    cookies = [c for c in self.allCookies()
                     if self.is_domain_the_same(current_url.toString(), self.cookie_url(c))]
    self.setAllCookies(cookies)
```

And here I have the problem that I don't know how to get URL of the current page...

Would be cool if you could help me here =)

**Comment by moozzz** [comment]
@Carpetsmoker, I checked what you suggested for config/websettings.py on different websites and it works really well. Perhaps we don't need any custom, otto-like code for handling third party cookies...

**Comment by The-Compiler** [comment]
Indeed this was much simpler than I thought it'd be. Thanks @moozzz and @Carpetsmoker!

**Comment by moozzz** [comment]
The code works great! I tested it with all sites I normally have in my tabs (except for facebook and sourceforge, because of the known reasons =D =D =D). Thanks a lot! I've gained a lot of experience while trying to make this task.

**Comment by Phantop** [comment]
Is there any way to bring this back under QTWebEngine?

**Comment by The-Compiler** [comment]
@Phantop once PyQt 5.11 is out, see #3010
