### ISSUE TITLE
How can I use <Space> in a keybinding?

### ISSUE THREAD

**Issue by fdietze** [The-Compiler/qutebrowser#610]

**Comment by The-Compiler** [comment]
Whoops - it seems I somehow missed this issue - sorry! You can use it just like that, e.g. `:bind <Space> open qutebrowser.org` works as intended here. What exactly are you having trouble with?

**Comment by fdietze** [comment]
Hmm, your example works for me, but I cannot get `:bind <Space><Space>r restart` working.

**Comment by The-Compiler** [comment]
Hm, true. Currently there are two kinds of keybindings: keychains (like `gg`) and "special" bindings with `<...>`, e.g. `<Space>` or `<Ctrl-x>`. You can't use special bindings in keychains, and you can't chain special bindings. This might change in the future, see #319.

Unfortunately you can't bind `  r` (i.e. literal spaces) either, because of the way `:bind` splits arguments, and because of how `keys.conf` strips leading/trailing spaces. This might change when the config gets converted to YAML, see #499.

**Comment by HolySmoke86** [comment]
link #2044
