### ISSUE TITLE
In hint-mode, bind shifted letters to open new tab (or window or background or whatever)

### ISSUE THREAD

**Issue by mgraham** [The-Compiler/qutebrowser#636]
In hint mode, if a hint is labeled "gaf", then typing "gaf" or "GAF" does the same thing.  Could these be split into separate actions?

For instance, the unshifted version could be to open the link in the same tab, and the secondary (shifted) action could be to open in a new tab.

**Comment by The-Compiler** [comment]
I want to use upper-case letters to filter hint texts, see #577. But I guess an option could be added so both is possible. What do you think?

**Comment by mgraham** [comment]
Hmmm..  I'm not sure I understand what hint filtering would do?

**Comment by The-Compiler** [comment]
You can try it out by using `:set hints mode number`, and then when hinting, type the start of a link text - e.g. when I use hinting here and type `m`, only the links for `mgraham` and `milestone` remain.

**Comment by The-Compiler** [comment]
You can try it out by using `:set hints mode number`, and then when hinting, type the start of a link text - e.g. when I use hinting here and type `m`, only the links for `mgraham` and `milestone` remain.

**Comment by mgraham** [comment]
Interesting!  Yes I would probably want to use both features :/

**Comment by noahrama** [comment]
i like this idea very much. ie. f + Shift <hint> = open in new tab. I often forget to type 'F' instead of 'f'.

**Comment by The-Compiler** [comment]
I forgot when this was added, but there are `<Ctrl-f>` and `<Ctrl-b>` bindings to switch between hinting modes during hinting - I think that's sufficient.

**Comment by Aster89** [comment]
Assume I hit `fa` in a page where hints are longer than one letter. `<Ctrl-b>`does not a good job.

  - As soon as <kbd>Ctrl</kbd> is hit, the first letter(s) of the hint get lost. IMHO a desirable behavior for what is entered after the initial `f` is that any of the letters being capital switches to "Follow hint in new tab" (see Vimium).
   - (I hope not be wrong in assuming that most qutebrowser's users are Vim users. If I'm right...) We are more accustomed to hit <kbd>Esc</kbd> than <kbd>Ctrl</kbd>; at the same time I think anyone makes a massive use of <kbd>Shift</kbd>s as compared to <kbd>Ctrl</kbd>s; in addition, the latter keys are also usually farther from the homerows as compared to the formers. All this is to say: given I typed `fa` instead of `Fa` in a two letter-hinted page (since my hands are not so slower than my thought) why should I bother pressing <kbd>Ctrl</kbd>+<kbd>B</kbd> ad retype `a` again instead of hitting <kbd>Esc</kbd> and start all over from `F`? It's only one keystroke less than <kbd>Esc</kbd><kbd>Shift</kbd>+<kbd>F</kbd>, not to mention that `f` and `F`, both on <kbd>F</kbd>, are the commands to follow links, not `b`.

**Comment by WloHu** [comment]
How I can enable this feature to filter hint text in `letter` mode? I can't find it anywhere.

In regards to this I have a question: is it possible that I can use uppercase letters for hints and lowercase letters for filtering hint text and vice versa? From VimFx I was used to type things like `fsettings` instead `f<whatever-hint>` on pages that I often use.

**Comment by tgharib** [comment]
I find that I sometimes press "f" before "shift", so I put `config.bind("G", "hint all tab-bg", mode="hint")` in my `config.py`. My muscle memory to open new tab in background is "shift" + "f" + "g", and it will still work even if I do "f" + "shift" + "g".
