### ISSUE TITLE
hints: More intelligent clicking

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#70]
Clicking on hints currently has some shortcomings:

* Clicking in the middle of form fields sets the cursor to a weird position
* Clicking on line-wrapped (2-line) links doesn't work because we only can get the outline rectangle

Maybe we should use javascript for this part instead?

**Comment by The-Compiler** [comment]
Using javascript and the [click() DOM method](http://www.w3schools.com/jsref/met_html_click.asp) is probably a good idea. Though I want test cases for clicking before I do any changes...

http://www.nonobtrusive.com/2011/11/29/programatically-fire-crossbrowser-click-event-with-javascript/

**Comment by lahwaacz** [comment]
The `click()` method on `<a>` element will probably not work if it has a `0px x 0px` size. This can happen in WebKit if the `<a>` element contains some other block element, see https://github.com/The-Compiler/qutebrowser/issues/1298#issuecomment-181982196.

**Comment by lahwaacz** [comment]
Note that the first point in the original post has been solved by 91b43c5cef36e84b78cc923ed2087c9df50a58c7 and 0fcd016427953bbd0859046594f10cf1f8260752, the second point by #1433. So in a way this could be closed since the clicking is now "more intelligent", the only remaining problem is clicking iframes to get a focus (#1525).

**Comment by The-Compiler** [comment]
Right, closing this!
