### ISSUE TITLE
<Esc> should probably break the keychain

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#716]
I have `partial-timeout` set to `0` (no timeout)

If I type: `g<Esc>`, if will not "break" the keychain, the `g` wll stay in the bottom-right corner.
If I then type `gt` again, I've effectivly typed `ggt`, and end up with a "partial" `t` in the bottom-right corner.

I found this rather unexpected; in Vim, this *does* break the keychain. I would expect `g<Esc>gt` to execute `gt`.

**Comment by The-Compiler** [comment]
This is actually implemented (but broken)...

From `keyinput/basekeyparser.py`:

```python
def _handle_single_key(self, e):
    // [...]

    if key == Qt.Key_Escape:
        self._debug_log("Escape pressed, discarding '{}'.".format(
            self._keystring))
        self._keystring = ''
        return self.Match.none
```

This doesn't work anymore because `<Escape>` was bound to clear the current search in 75ac9cce49271967ca3042bd7b368d55c6785a9a.

I guess that hardcoded binding should be removed, and instead a new hidden `clear-keychain` command should be added - then the default binding can be changed to do both.

**Comment by Carpetsmoker** [comment]
I also just noticed that the keys are persists when navigating. So if I press `y`, and then click a link in the current tab, the `y` will stay in the bottom-right.

I would expect this to be cleared by the mouse action?
