### ISSUE TITLE
Automatic history completion is very slow when shrink=true

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#734]
Automatic history completion is very slow when `shrink=true`. If I type `ow` it takes about 3 seconds:

    14:12:54 DEBUG    completion completer:_get_new_completion:165 completions: *url*
    14:12:57 DEBUG    completion debug:log_time:236 Setting filter pattern took 2.986237 seconds.

This is *only* slow if shrink is set to `true`. If it's `false`, it's very fast.  I'm guessing qutebrowser does a lot of unnecessary updates to the layout?

My history is 11,861 lines, 8,533 of which have a `w`, and `completion web-history-max-items=1000`

**Comment by The-Compiler** [comment]
The culprit here is in `completionwidget.py:CompletionView:set_model`.

That connects the `rowsRemoved` and `rowsInserted` signals to `self.maybe_resize_completion` which resizes the completion if needed (by calling `mainwindow.py:MainWindow:resize_completion`):

```python
model.rowsRemoved.connect(self.maybe_resize_completion)
model.rowsInserted.connect(self.maybe_resize_completion)
```

There are two problems with that:

* The view will get resized *every time* an item is inserted or removed, which is... stupid. Instead, it should get resized when the filter pattern or the model is changed. (That will however not work when new entries are added at runtime - but I think that's okay... otherwise, that signal should get disconnected while filtering).
* The signals will get connected multiple times, as the models are singletons - i.e. if you do `:open f`, then get out of the completion and do the same thing again, those signals will be connected *twice*, and the whole dance above happens twice.

**Comment by The-Compiler** [comment]
Profiling confirms that - with `set_model` called only once, `maybe_resize_completion` gets called over 3000 times.
