### ISSUE TITLE
:help :spawn gives incorrect error message

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#763]
After using `:help :spawn` I get:

> Problem occurred while loading the URL qute://help/commands.html#spawn
>
> [Errno 5] Input/output error: 'qutebrowser/html/doc/index.html'

After pressing `r` to reload, I get:

> [Errno 11] Resource temporarily unavailable: 'qutebrowser/html/doc/index.html'

After pressing `r` a few more times, I alternate between Errno 5 and 11, before I finally get:

> This most likely means the documentation was not generated properly. If you
> are running qutebrowser from the git repository, please run
> scripts/asciidoc2html.py. If you're running a released version this is a bug,
> please use :report to report it.

And pressing `r` again makes it alternate again.

In addition, I'm *not* running this from git. I did a "proper" install with `./setup.py build`, `sudo ./setup.py install`, so I'm not sure  why I'm getting this message. The message isn't very helpful in that it doesn't tell me which directory it's trying to search `/usr/share/qutebrowser`? `/usr/share/doc/qutebrowser/`? Somewhere else?

**Comment by The-Compiler** [comment]
I've ever seen those error messages - could you show the debug log after you refreshed a few times?

"From the git repository" means "using the repository instead of a release". For releases, the documentation comes pre-generated.

It'll search in the qutebrowser install dir, i.e. probably something like `/usr/lib/python3.4/site-packages/qutebrowser/html/doc/`.

Probably `setup.py` should refuse to run when the documentation was not found... but that'd make things harder for the CI (Travis/buildbot/AppVeyor).

**Comment by Carpetsmoker** [comment]
Here's a fix:

	diff --git i/qutebrowser/browser/network/qutescheme.py w/qutebrowser/browser/network/qutescheme.py
	index 7a9f3bf..71ee16d 100644
	--- i/qutebrowser/browser/network/qutescheme.py
	+++ w/qutebrowser/browser/network/qutescheme.py
	@@ -153,7 +153,7 @@ def qute_help(win_id, request):
		"""Handler for qute:help. Return HTML content as bytes."""
		try:
			utils.read_file('html/doc/index.html')
	-    except FileNotFoundError:
	+    except (FileNotFoundError, NotADirectoryError, OSError, BlockingIOError):
			html = jinja.env.get_template('error.html').render(
				title="Error while loading documentation",
				url=request.url().toDisplayString(),

Note: I was only able to reproduce this when running qutebrowser 'installed', not when running it from git.

Can't we just commit the generated html files in git by the way?

**Comment by The-Compiler** [comment]
I don't understand how this fix could work... If such an exception was really raised there, wouldn't the crash dialog be shown rather than a "Problem occurred while loading the URL" page?

> Can't we just commit the generated html files in git by the way?

I'd prefer not to - the autogenerated `.asciidoc` files are already a burden and I hope to get rid of them at some point. Generated HTML files are included with every release, so if someone is on `-git`, I think they'll just have to live with having to install asciidoc and generate the docs :wink:

**Comment by Carpetsmoker** [comment]
> I don't understand how this fix could work... If such an exception was really raised there, wouldn't the crash dialog be shown rather than a "Problem occurred while loading the URL" page?

IIRC It ended up in the errorpage handler, so the exception probably gets caught somewhere? I don't know exactly how it ended up there either, I just grepped for "Error while loading documentation", and added `except Exception as e: print(e.__class__)` for testing...

**Comment by The-Compiler** [comment]
As I can't reproduce this, can you please confirm catching `OSError` only fixes the problem as well? The others should be subclasses of that anyways.

**Comment by Carpetsmoker** [comment]
Catching only `OSError` seems to work.
