### ISSUE TITLE
windows msi install : fatal error : pypeg requiered when launching qutebrowser

### ISSUE THREAD

**Issue by Darfeld** [The-Compiler/qutebrowser#776]
I used the msi installer for windows (32bits) and when I try to launch the browser, I get a Fatal Error: pypeg2 is requiered to run qutebrowser but could not be imported!

I then try to install python3 and even installed pypeg2 via pip, but to no effect.

**Comment by The-Compiler** [comment]
It seems I just don't had a 32bit version of pypeg2 installed on the machine I use to build the packages... 

cx_Freeze (the tool I use for packaging) doesn't treat that as a fatal error as there are many platform-specific packages which are missing.

This will be fixed with the next release (v0.2.2/v0.3) which will hopefully be in the next few days, but I have to think about how I could catch those kind of things earlier.

If you can, I suggest using the 64bit version instead. If that doesn't work and you don't want to wait, you could [install manually](https://github.com/The-Compiler/qutebrowser/blob/master/INSTALL.asciidoc#on-windows).

Installing pypeg2 with a different python install unfortunately won't help as the package is using its own Python copy.

Sorry!

**Comment by The-Compiler** [comment]
This took a bit more time than I thought as I [found a Python/Windows bug](http://bugs.python.org/issue24493) along the way - but now Windows binaries are built in a virtualenv with all dependencies installed - and also smoke-tested (open/close qutebrowser without errors) after that.
