### ISSUE TITLE
Inbox asking to update the browser

### ISSUE THREAD

**Issue by kirelagin** [The-Compiler/qutebrowser#780]
When I open [Google Inbox](https://inbox.google.com), it says:

> It's been a while since your browser was last updated. Please upgrade to the latest version to continue using Inbox.

I’m not sure what exactly they are talking about. Is it old QtWebKit or something else… any ideas?

**Comment by The-Compiler** [comment]
I'd guess they are parsing the user-agent... GitHub did that as well (and broke everything) because `Safari/538.1` is in it (which actually is the rendering engine), but `Version/...` is not (which is actually the browser Safari).

(GitHub then fixed it after I and some other qutebrowser users complained)

I suggest using `:set network user-agent` and finding something which works (e.g. Chromium)...

**Comment by kirelagin** [comment]
Right, sorry, I should have guessed that myself!
