### ISSUE TITLE
Any way to put the scroll percentage on the titlebar?

### ISSUE THREAD

**Issue by ersi-dnd** [The-Compiler/qutebrowser#894]
Right now the titlebar shows the page load percentage on the titlebar. Is it possible to move the scroll percentage from the statusbar to the titlebar?

**Comment by The-Compiler** [comment]
Do you mean the window title, displayed by your window manager?

You can customize it using the `ui -> window-title-format` setting - however there's no placehoder for the scroll percentage. It should be easy to add one, however.

**Comment by ersi-dnd** [comment]
Yes, I meant the titlebar that the window manager handles.

This kind of element is supposed to be available for Luakit, but I have not managed to make it work https://github.com/mason-larobina/luakit/wiki/Scroll-indicator-in-window-title

**Comment by The-Compiler** [comment]
There you go - thanks, @averrin!

**Comment by ersi-dnd** [comment]
{scroll_pos} in window-title-format works! 

Thank you :)

**Comment by averrin** [comment]
:+1: Imho, nice idea is hiding position if its equal "top", but if u decorate it with brackets it will by ugly=( Maybe we should add some special tag like {hide_false(scroll_pos)}.
But i am not user of this feature, so...

**Comment by The-Compiler** [comment]
If we go down that road we might as well use [jinja2](http://jinja.pocoo.org/docs/dev/) for title format (which is already used elsewhere) - but I think that's overkill :laughing:

**Comment by averrin** [comment]
Nice idea! But u r right - its overkill. E.g. because i havnt window title bar. I prefer thinking about some title filtration or abbreviation...

**Comment by The-Compiler** [comment]
Damn, that'd *also* be easy with jinja, e.g. `{{ title|truncate(10) }}`. Hmmm...

**Comment by ersi-dnd** [comment]
@averrin Imho, nice idea is hiding position if its equal "top", but if u decorate it with brackets it will by ugly=( 

I ended up using it this way,
`{perc} {scroll_pos} - {title}{title_sep}qutebrowser`

{perc} is autodecorated anyway, so when i see the titlebar beginning with a decorated percentage, i know the page is loading.. after loading {perc} vanishes, so when i see percentage undecorated, i know it's scroll position

**Comment by averrin** [comment]
So, you suggest
top = ''
50% = [50%]
bot = [bot]
?
But you wont be able use other decoration (e.g. brackets)

**Comment by Kingdread** [comment]
As another possibility, if you don't want to go full jinja, you can use the special [`__format__`](https://docs.python.org/3/reference/datamodel.html#object.__format__) method to provide finer-grained formatting, e.g. you could have `{scroll_pos:decoration=[]}` to expand to either `''` if you're at the top, or `'[50%]'`, that way you could still use other decorations without having the ugly `'[]'`. If you prefer brevity, you could do something like `{scroll_pos:[%s]}`.

That would mean though that you'd have to write a custom class that implements the right `__format__`  and pass that when changing the title instead of the raw `scroll_pos` (i.e. instead of `title.format(scroll_pos=scroll_pos)` you'd have something like `title.format(scroll_pos=ScrollPosFormatter(scroll_pos))`)

**Comment by The-Compiler** [comment]
That's an interesting idea! I have to check how some of those common use-cases could be done with jinja first (i.e. how simple it'd be to use for an user). If it's simple enough, I'm leaning towards jinja - we already use it anyways, and it means maximum flexibility without much work :wink:
