### ISSUE TITLE
Font family not being correctly understood.

### ISSUE THREAD

**Issue by woegjiub** [The-Compiler/qutebrowser#904]
For sites that require the use of the fallback "sans-serif", the system's default sans-serif font is not being used.

This can be seen on github, if one does not have any fonts other than Liberation Sans installed, and has an empty fontconfig.

Note that "sans" as a font-family *does* work under that circumstance.

**Comment by The-Compiler** [comment]
Are you seeing the same as in #252? That's actually an issue with the `clean` font on GitHub.

Either way, it's unfortunately a bug with the QtWebKit rendering engine used by qutebrowser, and is likely to be fixed with the QtWebEngine/Chromium backend in #666.

I could report this [upstream](https://bugreports.qt.io/), but chances are it'll just be ignored :worried:. I guess it's best to just wait until the QtWebEngine backend is ready - sorry!
