### ISSUE TITLE
EXIF rotation tag not respected.

### ISSUE THREAD

**Issue by daniel-lawrence-lu** [The-Compiler/qutebrowser#992]
Some JPEG files have a rotation tag indicating that the image should be displayed rotated by 90 degrees.

For example, view the following picture: https://upload.wikimedia.org/wikipedia/commons/0/0f/Interior_of_the_UBC_Student_Union_Building_05.jpg

In Chrome, Firefox, etc, the picture is rotated to portrait mode and displays correctly, but not in Qutebrowser.

**Comment by The-Compiler** [comment]
This is handled by QtWebKit - there were some changes regarding exif rotation (see [QTBUG-45552](https://bugreports.qt.io/browse/QTBUG-45552) for example), so I'm not really sure what the current state is.

Either way, qutebrowser won't be able to do anything about this, and it'll be fixed with the QtWebEngine backend (#666), so I'm closing this.
